### ISSUE TITLE
Vanilla bow fires two arrows

### ISSUE THREAD

**Issue by Dr-WeiAL** [chronosacaria/MCDungeonsWeapons#101]
**Describe the bug**
Subsequent shots after the vanilla bow hits the target will fire two arrows

**To Reproduce**
1. Shoot the target with a bow
2. shoot the target again

**Expected behavior**
make it normal

**Screenshots**
![image](https://user-images.githubusercontent.com/47446553/157038535-3fadc3b6-3be4-43c2-8cff-04cf4fed6ba5.png)

**Please complete the following information:**
 - OS: Windows
 - Launcher HMCL
 - Mod Version 4.2.3
 - Are you using a Modpack? No

**Additional context**

**Comment by chronosacaria** [comment]
@Dr-WeiAL Thanks for this issue report! You mention "see error", is there an actual error that you get along with the extra arrow that points to anything in particular that might help us narrow down what is happening?

**Comment by Dr-WeiAL** [comment]
This problem occurs when attacking any target, the bow is not enchanted, only this mod and modmenu are installed, is there anything else to add?
[latest.log](https://github.com/chronosacaria/MCDungeonsWeapons/files/8197857/latest.log)

**Comment by chronosacaria** [comment]
That's perfect! Thank you so much. We'll take a look at this today
