### ISSUE TITLE
Dual Wield Spam

### ISSUE THREAD

**Issue by TheSkeletonAppears** [chronosacaria/MCDungeonsWeapons#102]
**Describe the bug**
This occurs when you have a dual wield weapon like The Beginning and The End if you hold down right click the weapon in the off hand slot will spam this is really bad with the enigma resonator

**To Reproduce**
1. Go get a dual wield weapon like The Beginning and The End
2. Click on RMB

**Expected behavior**
It will spam non stop and the damage is not erm lets say the damage stays the same since the combat update you cant spam swords anymore well this breaks that rule

**Screenshots**

**Please complete the following information:**
 - OS: Windows 10
 - Launcher: Tlauncher (Premium account)
 - Mod Version MCDW 4.04
 - Are you using a Modpack? No

**Additional context**

**Comment by Kluzzio** [comment]
This is a known issue. Thank you for reporting it. We will be revisiting the entire dual wielding implementation so we will take this into account when doing so and hopefully be able to implement this feature.

**Comment by Kluzzio** [comment]
We are integrating Better Combat into MCDW for our 1.18 and our 1.19 branch. Part of this involves removing the dual wielding feature as it is now. We may re introduce it for if the user wishes not to have Better Combat in their mods. In the case that Better Combat is used though, the dual wielding will not be spammable.

**Comment by Kluzzio** [comment]
The fallback for Better Combat has working antispam so we gucci
