### ISSUE TITLE
Default Loot System, from looking at code, does not appear to be working

### ISSUE THREAD

**Issue by chronosacaria** [chronosacaria/MCDungeonsWeapons#106]
**Describe the bug**
Judging from the code from the [McdwNewLoottables.java](https://github.com/chronosacaria/MCDungeonsWeapons/blob/1.18/src/main/java/chronosacaria/mcdw/loottables/McdwNewLoottables.java) class, it does not appear that anything from the default loot tables would be generating. This is something that needs to be checked and corrected if it isn't working.

**To Reproduce**
1. Go to Creative World with Default Loot Table Settings
2. Use commands to call loot from any loottable that would have MCDW weapon in it
3. If weapons appear, this is a non-issue; if they do not, rewrite loottable code

**Expected behavior**
That weapons that do not have crafting recipes, such as the Coral Sword, should show up in loottables when using the default loot settings.

**Screenshots**
N/A

**Please complete the following information:**
 - OS: N/A
 - Launcher [e.g. Default, MultiMC, GDLauncher, etc.]: N/A
 - Mod Version [e.g. 4.0.3]: 4.2.5
 - Are you using a Modpack? [e.g. Yes, No; if Yes, which one]: No

**Additional context**
N/A

**Comment by Kluzzio** [comment]
Default Loot Table settings have weapons in chests. Only if this is disabled is there no way to get the uncraftable weapons. Therefore, this is a non-issue.
