### ISSUE TITLE
Some weapons have repair items that don't add durability

### ISSUE THREAD

**Issue by karlschmidt66** [chronosacaria/MCDungeonsWeapons#109]
Tried to repair sun's grace using a diamond. Anvil accepts the diamond as an item for repair and assigns a number of levels to repair it but does not increase the durability of the weapon. 

Steps to reproduce. 
Put a used sun's grace on an anvil with a diamond
Pickup repaired sun's grace

Expected behavior
Full repair

Actual behavior
Durability is the same but levels were spent in repair. 

OS Windows
Curseforge launcher
Mod Version 4.2.5
Modpack: DarkRPG Fabric V2.2

**Comment by chronosacaria** [comment]
I'll take a look at this in the morning, for sure! Thanks for catching this

**Comment by karlschmidt66** [comment]
Thanks!

**Comment by Kluzzio** [comment]
![image](https://user-images.githubusercontent.com/96443090/162468435-e9298a6d-d3dc-41ef-9baa-017d9ed2b58a.png)
There is no issue repairing on my end. A single diamond repairs 390 durability here. Therefore, this is a mod conflict. Please bring this up with the GamerPotion, who is the dev of your modpack as this is something that is on their end.
