### ISSUE TITLE
think i found another one, or someone did

### ISSUE THREAD

**Issue by superon** [chronosacaria/MCDungeonsWeapons#11]
v 2.1.1
https://pastebin.com/9nukpmw1
looks like onAnimaConduitKill this time, can't say if i was doing anything in particular but there was someone else on the server at the time this time and they said they'd just killed a sheep.
\o/

**Comment by chronosacaria** [comment]
I genuinely cannot express enough how grateful I am that you keep finding these things and bringing them to my attention. It is a massive help and I mean that sincerely! :)

**Comment by chronosacaria** [comment]
Huh? It is another piglin problem. Was anyone even in the Nether when this happened?

**Comment by superon** [comment]
i was in the nether

**Comment by chronosacaria** [comment]
Okay. I'm going to have to piglin-proof everything it seems. But this is good to know

**Comment by superon** [comment]
i had not long been killed and killed a pigman that had stolen my armour, didn't have an mcdw on it though

**Comment by superon** [comment]
odd yea, i was carrying a bow, i think the only mcdw i owned at the time... do you think it might make a difference that i'm having the weapons instantiated with a loot_table instead of having them crafted? rhetorical

**Comment by chronosacaria** [comment]
That is even stranger then because onAnimaConduitKill should only trigger if an item has the enchantment. It is actually the only enchantment other than Ricochet, right now, that does not have an innate presence

**Comment by chronosacaria** [comment]
I mean, anything is possible, especially since the enchantments can be added to loot items; but I don't know for sure

**Comment by chronosacaria** [comment]
Ahh, I found the problem, I think: 

healthRegained = (float) (getCurrentExperience((PlayerEntity) user) * (0.2 * level));

The game tried to heal the Piglin and it crashed

**Comment by superon** [comment]
o right, well anima_conduit is one of 3 enchants that i had no clue what they do.. so i guess it heals pigmen, or mobs at least :)

**Comment by chronosacaria** [comment]
It heals you based on the amount of experience you gain

I cannot get a piglin to pickup anything except gold things. Do you have another mod that changed them?

**Comment by superon** [comment]
hmm, i think some just don't pick up items, like the zombie mechanic, checking now about other possible mods...
right now nothing springs to mind

**Comment by chronosacaria** [comment]
Which version are you using, btw?

**Comment by superon** [comment]
2.1.1

**Comment by chronosacaria** [comment]
Okay. Just wanted to make sure. I have a version 2.2.0 that should hopefully fix that. I'll let you know once it is on Curseforge. There are a bunch of other goodies that I was about to release as well like lore on the items

**Comment by chronosacaria** [comment]
And a way to adjust attack strength based on a config file :)

**Comment by superon** [comment]
right so, i don't know what could be anything to do with this but here are possible potentials..
adventurez-1.1.5 adds its own piglin type mob, piglin beast and adjusts the piglin loot_table to add items into their "trades".
extraorigins-1.16.4-4 adds player buffs that mimic pigman type for the player in various ways.
netherroof-1.0.0 not piglin related maybe but it does change the way things spawn in the nether based on y level (so things don't spawn on the bedrock roof)
eldritch-mobs-1.5.4 add buffs to potentially all mobs randomly so this would be my best bet, i think there is a buff that allows them to steal weapons from a player.
apart from those i could not even guess but really could be anything as i don't know a lot about a lot of those included :/
Lore \o/ config \o/ awesome \o/

**Comment by chronosacaria** [comment]
It could be related to one of those. We'll see what happens, though. I won't close the issue until there have been several days without another issue. The new version is live now, btw: https://www.curseforge.com/minecraft/mc-mods/mcdw/files/3138826

**Comment by superon** [comment]
wonderful, will be testing tomorrow :)

**Comment by superon** [comment]
all seems superfine and splendid now after having tested for a few hours.... also, after more recently removing a mod that was behaving badly i discovered this https://www.curseforge.com/minecraft/mc-mods/piglib which i think more likely to be the initial culprit

**Comment by chronosacaria** [comment]
Nice! I'm going to close this out then :)
