### ISSUE TITLE
"Critical Hit" Enchantment is too powerful

### ISSUE THREAD

**Issue by milodakat** [chronosacaria/MCDungeonsWeapons#111]
The Critical Hit enchantment is broken due to how powerful it is. Even low damage melees can instant kill players with good armour. It needs to be rebalanced.

**Comment by chronosacaria** [comment]
What version are you on? Are you on a server? Has your server owner tweaked the damage? There is a template for a reason and there is not enough information for me to take anything from this report other than your opinion. Please provide more information, otherwise we cannot do anything with this. Thank you.

**Comment by Kluzzio** [comment]
We will look at making a potential change but yes, please use the template in the future. Your concern is a valid one, but the numbers we use is to stay as true to MC Dungeons as possible. We are potentially open to making the numbers configurable so we will touch base on that.

**Comment by Kluzzio** [comment]
Addressed in https://github.com/chronosacaria/MCDungeonsWeapons/commit/6a7f2f0a0bc0f7558931d371691c8f607cb4c276

**Comment by Kluzzio** [comment]
No further accommodations will be made without more information. Keep in mind that this mod serves to be vanilla+ and stacking enchantments endlessly on one weapon is not considered in balancing purposes. Nevertheless, an oversight on the implementation of Critical Hit was discovered and corrected. Additionally, a multiplicative stacking of mcdw enchants was changed. We have little to no control over mod priority though so there is only so much 'balancing' we can do without making the enchantments individually irrelevant. As such, this issue will be closed.
