### ISSUE TITLE
MC Dungeons Weapons/Armor don't appear in REI like stated

### ISSUE THREAD

**Issue by IDEZIHREE** [chronosacaria/MCDungeonsWeapons#112]
**Describe the bug**
Downloaded all of REI even mod compatibility workaround to see if that was the issue, MC Dungeons weapons and armor do not appear anywhere.

**To Reproduce**

**Expected behavior**
Hopefully get information on why the mod does not show thanks

**Screenshots**

**Please complete the following information:**
 - OS: windows]
 - Launcher: Default
 - Mod Version 4.2.5
 - Are you using a Modpack? [e.g. Yes, No; if Yes, which one]

**Additional context**

**Comment by Kluzzio** [comment]
Are you able to see the MCDW items in the creative menu?

If no: note that you must have all of the dependencies of the mod, you must have a paid copy of minecraft, and you must be using fabric.

If yes: It would be easier to provide tech support on this issue on the discord. Please join, and let us know when you can best be helped, your preferred language, and if you are comfortable joining vc. Thanks!

**Comment by IDEZIHREE** [comment]
Thank you. I did not see anywhere that you need to use fabric my apologies. You can close this request.
