### ISSUE TITLE
Skeletons deal too much damage - 1.18.1

### ISSUE THREAD

**Issue by Maja-dev** [chronosacaria/MCDungeonsWeapons#115]
**Describe the bug**
Skeletons deal a lot of damage

**To Reproduce**
Agro any skeleton, they hit you with 5 dmg in Full Netherite, 14 dmg in full Iron set on Normal, 17 on Normal with no armor

**Expected behavior**
Skeletons should deal ~2 dmg when in full iron.

**Video**
Full iron
https://streamable.com/2wi99a

No armor on Normal
https://streamable.com/ds0ue7

**Please complete the following information:**
 - Windows 11
 - Default launcher, 1.18.1 - Fabric Loader 0.14.0
 - MCDW - 4.3.0 - 1.18.1
 - Debugging with this mod only and new default config settings + Fabric API. Same problem with my personal modpack.
 

**Additional context**
This doesn't happen with MCDW deactivated when in debug with no other mods loaded. 
Here's a log of me creating a new flat world, getting oneshot by a skeleton on Normal with no armor and leaving.

[latest.log](https://github.com/chronosacaria/MCDungeonsWeapons/files/8545228/latest.log)

**Comment by Kluzzio** [comment]
This was me, sorry! I even already fixed this issue in https://github.com/chronosacaria/MCDungeonsWeapons/commit/f5f5b961e9d86999c468ea12b1a5f093dc19bbe6

but I did not realize the repercussions of this lack of change. Thanks for finding and reporting this!
