### ISSUE TITLE
Glitching weapons when enchanted

### ISSUE THREAD

**Issue by xHivex** [chronosacaria/MCDungeonsWeapons#116]
While holding a weapon the enchants are glitching out and duplicating the item if throw it and move the item before you pick it back you.

https://user-images.githubusercontent.com/1533447/164915050-c5737616-e82f-4ec9-b1b2-f97faa9bff92.mp4

https://user-images.githubusercontent.com/1533447/164915058-906b29f2-cf74-4072-a908-a4ac42c88c87.mp4

Minecraft: 1.18.1 
Fabric Loader: 0.13.3
Mod Version: mcdw 4.3.0
Other mods: https://pastebin.com/dfNNEYQS

**Comment by chronosacaria** [comment]
That's a lot of mods! I've not noticed this happen with just MCDW alone, but I will look into this. I suspect, however, that we're looking at some kind of mod conflict

**Comment by zerevoidd** [comment]
having the same issue

**Comment by chronosacaria** [comment]
@zerevoidd Could you provide your mod list, please?

**Comment by zerevoidd** [comment]
how do I do that without picking out and writing down every single mod individually

**Comment by Kluzzio** [comment]
By going to your mods folder and taking screenshots of the mods and putting it here

**Comment by zerevoidd** [comment]
https://pastebin.com/Bs6Cz0J4

**Comment by SkyleKayma** [comment]
Same problem reproduced here. 
Below is my modlist:
https://pastebin.com/0QMR60yd

**Comment by chronosacaria** [comment]
@xHivex @SkyleKayma @zerevoidd Would any of y'all be able to hop into the Discord and help test a branch that might resolve this issue? https://discord.gg/J9GGuh6eyq

**Comment by zerevoidd** [comment]
my discord is zere#8486, i am already in the discord
