### ISSUE TITLE
enchant

### ISSUE THREAD

**Issue by milodakat** [chronosacaria/MCDungeonsWeapons#118]
**Describe the bug**
Weapons with inbuilt enchantments can be de-enchanted at a grindstone. Some weapons change name colour when enchanted (hammer of gravity) while others stay the same colour (soul fist) These weapons reset their enchantment to default after rejoining the game (whether the item is in item frame or inventory)

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/55367150/166069860-53deefc0-efcc-419c-bbd2-b130b227d820.png)
![image](https://user-images.githubusercontent.com/55367150/166070127-d715d003-7e2f-4391-9923-919db8b1b925.png)
![image](https://user-images.githubusercontent.com/55367150/166070070-1ec6c8df-3c53-4e26-8acf-3183236e06a3.png)
![image](https://user-images.githubusercontent.com/55367150/166070637-31daf5dc-ff75-400e-8bb7-778864d78704.png)

**Please complete the following information:**
 - OS: Windows
 - Launcher:  Default
 - Mod Version: 4.3.1
 - Are you using a Modpack? idk

**Additional context**
Only tested with the Hammer of Gravity, Shear Dagger and Soul Fist, happened for all of them

**Comment by chronosacaria** [comment]
Upon further testing, this is almost definitely being caused by a mod conflict as I cannot reproduce this in an environment with just MCDW. Please work your way through your mods in an A-B fashion until you are able to determine which mod is causing the issue. Thank you
