### ISSUE TITLE
Disabling crafts with craft tweaker?

### ISSUE THREAD

**Issue by jirisek3** [chronosacaria/MCDungeonsWeapons#119]
So me and my friends want to add god weapons for our server but want to disable all the crafts so that the only way someone can get them is by doing a ritual for their god. So I need to disable all the crafting recipe for the weapons and will be thankful for any help

**Comment by chronosacaria** [comment]
Unless a description is provided in the next hour, this issue will be closed. Thank you.

**Comment by chronosacaria** [comment]
@jirisek3

**Comment by chronosacaria** [comment]
@jirisek3 This might be something that would be better to ask for help on the Discord as there are others who might make use of CraftTweaker. I am more familiar with KubeJS. I would highly suggest checking out the Discord, which can be found here: [https://discord.gg/ARYuZ4f24h](https://discord.gg/ARYuZ4f24h)

**Comment by Kluzzio** [comment]
User referred to Discord. User joined Discord. Huzzah
