### ISSUE TITLE
How does the dual wield with soul fist work?

### ISSUE THREAD

**Issue by CarTDC** [chronosacaria/MCDungeonsWeapons#120]
It doesn't put it in my offhand if its supposed to

**Comment by chronosacaria** [comment]
@CarTDC Please provide acquitted information as to your question. As best as I can tell, you are simply not putting the Soul Fist into your offhand. Should there not be further clarification on this issue within an hour, this issue shall be closed.

**Comment by CarTDC** [comment]
I crafted 2 soul fist and put one in my main hand and one in my offhand am I supposed to do that

**Comment by CarTDC** [comment]
> @CarTDC Please provide acquitted information as to your question. As best as I can tell, you are simply not putting the Soul Fist into your offhand. Should there not be further clarification on this issue within an hour, this issue shall be closed.

I thought it would automatically put a soul fist in both hands when equipped

**Comment by chronosacaria** [comment]
Ah, yeah, no. You need to manually equip both. You can technically equip _any_ two dual wield weapons, though there is a bug that we are working on fixing so I would not suggest mixing and matching at this time. Thanks for quickly responding. 

As this question has been answered, I shall close this issue.
