### ISSUE TITLE
Ticking Entity

### ISSUE THREAD

**Issue by TheButterbrotMan** [chronosacaria/MCDungeonsWeapons#121]
**Describe the bug**
Server crashes randomly, and is unable to start again after that.

**Please complete the following information:**
 - OS: [Linux (Server?)]
 - Launcher [Curseforge]
 - Mod Version [4.3.2]
 - Are you using a Modpack? [Yes, Deathdusk]

**Additional context**
https://bytebin.lucko.me/HTjEcNn9Hb
https://bytebin.lucko.me/WG3jhE03vq

**Comment by chronosacaria** [comment]
This isn't enough information to go on. What were you doing when the server crashed? There doesn't appear to be any MCDW enchantments on the arrow so I am confused as to why you thought it was us? Is there something I'm missing here?

**Comment by chronosacaria** [comment]
It would also appear that the updated log you provided relates to tridents, which we don't even touch. It would seem to me that there is something else going on

**Comment by TheButterbrotMan** [comment]
Any idea how i could figure out then what is touching the tridents?

**Comment by TheButterbrotMan** [comment]
> This isn't enough information to go on. What were you doing when the server crashed? There doesn't appear to be any MCDW enchantments on the arrow so I am confused as to why you thought it was us? Is there something I'm missing here?

I dont have more, i just waked up and had thousands of this logs inside my crashreports folder. So i did just go by luck and opened a issue here.

**Comment by Kluzzio** [comment]
Well it's a class cast exception, but I looked at instances of our code relating to PPE's and we shouldn't be causing any issue here. I also tested it with 100% proc rate on our enchants and nothing crashed.

You are dealing with a mod for some reason having an empty list that java can't recognize as empty that is referenced in trying to find the 0th element at the OnEntityHit method.

To find out what mod is causing the issue, I would recommend splitting the mods in half, and testing to see if you can replicate the crash recursively until you are able to narrow it down to one mod. I am fairly confident it is not us though

**Comment by Kluzzio** [comment]
Well, since there is nothing that supports that this would be us, this issue will be closed. Best of luck in finding out what happened though.
