### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by I5268** [chronosacaria/MCDungeonsWeapons#125]
**Is your feature request related to a problem? Please describe.**
there are too many enchants and it is too hard to keep track of what goes on what

**Describe the solution you'd like**
i woold like some sort of guide book that hase different sections for example one that is all about the different types of bows and what they all actually do the amout of damage that they do, the enchants that are for bows and what enchants are compatable with one another and wich arrent
**Describe alternatives you've considered**
you could also wright a small description to the enchants (like with all of the items) that says what the enchant goes on, what it does and what it is not compatable with

**Additional context**

**Comment by chronosacaria** [comment]
@I5268, please edit this issue so that it is using the template properly. That way it is easier to read rather than that long title.

**Comment by I5268** [comment]
sorry first time using github

**Comment by I5268** [comment]
@chronosacaria  i belive i have done what you asked

**Comment by chronosacaria** [comment]
That's fantastic! Thank you, so much!

**Comment by I5268** [comment]
dose that meen that you will add it?

**Comment by chronosacaria** [comment]
@I5268 Since you have closed this issue, we shall take this to mean that this is no longer a requested feature. Please note that just because a request is made, it does not mean that it will be added. That is why it is called a "request"

**Comment by I5268** [comment]
it is still a request :)

**Comment by Kluzzio** [comment]
Enchants are now described in the wiki thanks to pizzaspren. As such this issue will now be closed as we will not in the foreseeable future be adding an in game item that gives descriptions as you have described.
