### ISSUE TITLE
Make Webshot not spawn string 

### ISSUE THREAD

**Issue by MoshSD** [chronosacaria/MCDungeonsWeapons#126]
**Describe the bug**
webshot spawns cobweb that drops string

**To Reproduce**
get bow with webshot
shoot floor
mine with sword 
profit

**Expected behavior**
free string infinite

**Screenshots**
N/A

**Please complete the following information:**
 - OS: Windows
 - Launcher Default
 - Mod Version 4.4.0
 - Are you using a yes?  Custom.

**Additional context**
Copy paste cobweb code, make it despawn over time and stop it from dropping string

**Comment by Kluzzio** [comment]
Done here: https://github.com/chronosacaria/MCDungeonsWeapons/commit/dec147b053a499e6eb771d2f1b8cd627f87449c9

Won't implement in main branch though, at least for now.
