### ISSUE TITLE
The spear has the capability to strip logs? 

### ISSUE THREAD

**Issue by AzureMonument** [chronosacaria/MCDungeonsWeapons#13]
So I just accidentally right-clicked a Cika log, added by the Biomes You'll Go mod with my spear and ended up stripping it. Confused I tried the log next to it as a test and I stripped it again. I then pulled out a vanilla oak log and also stripped it with the spear.

I... don't think this is intended?

**Comment by chronosacaria** [comment]
lol, it is not intended, but it is currently built from an axe so that it has shield breaking potential. I am working on a way to have the shield breaking without the axe preset. Thanks for making an issue report, because this is, indeed, a bug
