### ISSUE TITLE
how can i use the translation

### ISSUE THREAD

**Issue by zombieowo** [chronosacaria/MCDungeonsWeapons#133]
I don't know how to switch languages

**Comment by chronosacaria** [comment]
This is less of an MCDW question and more of a general Minecraft question. Generally, these would be better handled in the Discord. However, depending on the language your game is already in it will obviously change the words used for the buttons, but, you go to Options -> Language and then select the language you want. 

Keep in mind that the only complete translations for MCDW are English and Simplified Chinese. If you would like to contribute to translating MCDW into your language, let us know and we can walk you through how to do that. 

As this is a question and not an issue and as the question is answered by this response, this issue shall be closed.
