### ISSUE TITLE
A way to turn off crafting recipes [Feature Request]

### ISSUE THREAD

**Issue by JTModel3** [chronosacaria/MCDungeonsWeapons#135]
**Is your feature request related to a problem? Please describe.**
I would like to use these weapons as 'God weapons' on my server but I would like to be able to remove there crafting recipes.

**Comment by chronosacaria** [comment]
@JoiningToast We are considering a way to possibly do this, but this is also possible using KubeJS. If you need help setting that up, I highly encourage you to stop by the Discord and we can help you get set up with that

**Comment by Kluzzio** [comment]
Because the expected way to do this is KubeJS, this will not be worked on.
