### ISSUE TITLE
I tried to modify the config file of the enchant giver, but every time I restart the game, he will reset to the original settings.

### ISSUE THREAD

**Issue by LILPRINCES** [chronosacaria/MCDungeonsWeapons#139]
No other mod are loaded

cloth-config-6.2.62-fabric
mcdw-4.4.1
fabric-api-0.58.0+1.18.2

**Comment by Kluzzio** [comment]
You are correct, this is an issue we fixed in a previous version and then forgot to restore when we switched from force enchants back to enchant giver. As such, this issue will be resolved in the next release.
