### ISSUE TITLE
Bag of souls enchantment multiply exp collected after dying

### ISSUE THREAD

**Issue by DanniX01** [chronosacaria/MCDungeonsWeapons#143]
**Describe the bug**
When using this alongside Universal Graves mod the effect of this enchantment is applied to the exp collected by the gravestone, multiplying the original Exp. Not sure if it happens with other gravestones mods.

**To Reproduce**
1. Have an armour enchanted with Bag of Souls.
2. Have Universal Graves mod installed.
3. Die.
4. Collect items from the gravestone.

**Expected behavior**
Exp collected from grave shouldn't be affected by the enchantment

**Screenshots**
![image](https://user-images.githubusercontent.com/36800081/185724731-7d1363bb-3466-42ca-bf42-e678c2c3504a.png)
*This is what happens when someone abuses of this*

**Please complete the following information:**
 - OS: Windows 10 x64
 - Launcher: SKLauncher
 - Mod Version: 2.0.1
 - Are you using a Modpack? No

**Additional context**

**Comment by chronosacaria** [comment]
🤔 That's definitely an interesting issue. We'll take a look at this. Thanks

**Comment by chronosacaria** [comment]
@DanniX01 Please reopen this issue in MCDA. Soul Devourer is from MCDW, Bag of Souls is from MCDA

**Comment by Kluzzio** [comment]
After some discussion, this is intended behavior on our end. The graves drop xp orbs so it makes sense that the xp multiplication effects should multiply it. We may bring this up with mentioned grave mod but this will not be worked on from our end.

**Comment by DanniX01** [comment]
> @DanniX01 Please reopen this issue in MCDA. Soul Devourer is from MCDW, Bag of Souls is from MCDA

Sorry I got confused. Next time I will make sure to look at the correct mod name.

> After some discussion, this is intended behavior on our end. The graves drop xp orbs so it makes sense that the xp multiplication effects should multiply it. We may bring this up with mentioned grave mod but this will not be worked on from our end.

I see. I fixed the issue using an option in the mentioned graves mod that uses an alternative orb item for the xp stored in the grave so it won't apply the enchantment effect. 

Thanks for replying, despite I opened the issue here!
