### ISSUE TITLE
Game crashes if an arrow shot from Nautilus Crossbow touches water

### ISSUE THREAD

**Issue by BluStryx8** [chronosacaria/MCDungeonsWeapons#151]
Upon shooting an arrow into water with the Nautilus Crossbow, the game will immediately crash. Attempting to reload the world will also result in an immediate crash when the world loads. Error message is as follows:
"""
The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "java.lang.Float.floatValue()" because the return value of "org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable.getReturnValue()" is null
"""

**To Reproduce**
1. Grab a Nautilus Crossbow
2. Shoot into a decently sized pool of water
3. Game crash
(note: if the arrow hits a wall immediately after entering water, the game will not crash)

**Expected behavior**
Not crashing. I assume this has to do something with the Nautilus Crossbow being unaffected by water, but ironically, it's being very adversely affected by water.

**Please complete the following information:**
 - OS: Windows
 - Launcher: Default
 - Mod Version: mcdw-5.0.1-1.18.jar
 - Are you using a Modpack? No

**Additional context**
Originally found this error while messing around creating a modpack, but did further testing and the issue still persisted after loading only MCDW and repeating the process, so it's almost certainly not a modpack issue.

**Comment by chronosacaria** [comment]
Thank you for bringing this to our attention
