### ISSUE TITLE
Most shortbows held in left hand face the wrong direction

### ISSUE THREAD

**Issue by BluStryx8** [chronosacaria/MCDungeonsWeapons#152]
**Describe the bug**
"Mechanical Shortbow", "The Purple Storm", and "Shortbow" weapons face left, instead of right, when drawing an arrow with them when they are held in the left hand.

**To Reproduce**
1. Place any of the three shortbows listed into your left hand. It does not matter if you set skin customisation to have a main left hand, or you are using the offhand: so long as the bow is in the left hand, it will suffice.
2. Right click to draw an arrow.
3. See error

**Expected behavior**
Bow should just be facing right.

**Screenshots**
![2022-08-30_23 53 29](https://user-images.githubusercontent.com/54874050/187455888-9df628f6-1b1c-4387-9045-434cd2bac0ee.png)
![2022-08-30_23 53 14](https://user-images.githubusercontent.com/54874050/187455869-8644a265-60ba-4a83-976c-f7fc7e4b773a.png)
![2022-08-30_23 53 00](https://user-images.githubusercontent.com/54874050/187455853-7e5bd454-b5e7-43a2-abac-4df230390fbc.png)

 - OS: Windows
 - Launcher: Default
 - Mod Version: mcdw-5.0.1-1.18.jar
 - Are you using a Modpack? Yes, custom

**Additional context**
Modpack probably isn't relevant to the issue since there's no resource packs downloaded that directly mess with MCDW's bows, nor is there a mod that would affect how items are rendered in hand
Also, Love Spell Bow is the only shortbow not affected by this.

**Comment by BluStryx8** [comment]
Tested with MCDW alone, issue persists.

**Comment by chronosacaria** [comment]
Oh wow, that's weird. Thanks again! You finding this issues is a tremendous aid!
