### ISSUE TITLE
Crossbow rendering issues when loading

### ISSUE THREAD

**Issue by BluStryx8** [chronosacaria/MCDungeonsWeapons#153]
**Describe the bug**
When loading any crossbow, the crossbow shrinks upon charging to max (when releasing right click would load an arrow into the crossbow).
However, the Nautical Crossbow and Harpoon Crossbow disappear while loading, only reappearing when charging to max.

**To Reproduce**
1. Take any crossbow.
2. Hold right click to load.
3. When at max charge, the crossbow will automatically shrink.
(If using the Nautical or Harpoon Crossbows, the crossbow will disappear while charging instead, and reappear at max charge)

**Expected behavior**
Staying the same size at the end of loading animation

**Screenshots**
![2022-08-31_00 24 39](https://user-images.githubusercontent.com/54874050/187463775-0e449ce3-0797-4962-857e-c8deb8f19142.png)
![2022-08-31_00 24 28](https://user-images.githubusercontent.com/54874050/187463754-4b12502f-d195-4fa3-8131-6e6d48506e33.png)

 - OS: Windows
 - Launcher: Default
 - Mod Version: mcdw-5.0.1-1.18.jar
 - Are you using a Modpack? No

**Additional context**
While we're here, some extra small issues:
- Various crossbows do not centre on screen while loaded with a firework rocket:
Auto Crossbow, Azure Seeker, Baby Crossbow, Burst Crossbow, Butterfly Crossbow, Cog Crossbow, Corrupted Crossbow, Harpoon Crossbow, Harp Crossbow, Nautical Crossbow, Rapid Crossbow
![2022-08-31_00 25 50](https://user-images.githubusercontent.com/54874050/187464201-fb736be9-e3d7-4125-9f0d-4a65ff6003a0.png)
![2022-08-31_00 26 01](https://user-images.githubusercontent.com/54874050/187464226-b5997b7d-80d9-4e36-9225-4771c7c86bc5.png)
- Various bows resize in the hotbar while charging an arrow:
Ancient Bow, Haunted Bow, Phantom Bow, Shivering Bow, Twin Bow, Twisting Vine Bow, Web Bow, Weeping Vine Bow, Mechanical Shortbow, The Purple Storm, Shortbow
![2022-08-31_00 31 52](https://user-images.githubusercontent.com/54874050/187464880-b3529688-9177-4b70-845a-eeb204690e3a.png)
![2022-08-31_00 32 03](https://user-images.githubusercontent.com/54874050/187464901-88379ac3-5bf8-4aab-acf1-9b62349b241e.png)

**Comment by chronosacaria** [comment]
Mate, you're awesome! Keep 'em coming! This is phenomenal feedback! Thank you!

**Comment by DaFuqs** [comment]
HeldItemRenderer has lots of Bow and Crossbow methods hardcoded. Unmojanking this is possible, but pain

**Comment by DaFuqs** [comment]
After [way more mixin than I am comfortable with](https://github.com/DaFuqs/Spectrum/commit/9305ddb5041a3bab5c53a64e70ae7ec7c5809418) I got bow and crossbow animations working flawlessly.

While I was at it, I also added some useful attributes to bows and crossbows. Maybe those are interesting for you, too. I could make a small lib out of them, if there is interest.

Bow Attributes:
https://github.com/DaFuqs/Spectrum/blob/1.18.2/src/main/java/de/dafuqs/spectrum/items/tools/SpectrumBowItem.java

Crossbow Attributes:
https://github.com/DaFuqs/Spectrum/blob/1.18.2/src/main/java/de/dafuqs/spectrum/items/tools/SpectrumCrossbowItem.java

**Comment by DaFuqs** [comment]
(alternatively feel free to steal those. Since it's not using any redirects all mods should be perfectly compatible 👌)

**Comment by BluStryx8** [comment]
Hello, back again after a few months (since I took a break from messing with mods to focus on life stuff)
1.19.2 version of the mod has a lot of rendering issues, so I've taken the time to group crossbow rendering errors.

- Still resizes in hotbar while charging: Ancient Bow, Twisting Vine Bow, Weeping Vine Bow, Shortbow
- Renders at the top of the screen while loading: Auto Crossbow, Azure Seeker, Baby Crossbow, Burst Crossbow, Cog Crossbow, Corrupted Crossbow, Harpoon Crossbow, Harp Crossbow, Nautical Crossbow
- Shifts to the right, and shrinks when charged but not loaded: Butterfly Crossbow, Rapid Crossbow
- Tilts downwards while loading, and shrinks when charged but not loaded: Doom Crossbow, Heavy Crossbow, Lightning Harp Crossbow, Scatter Crossbow, Slayer Crossbow
- Incorrectly shows in the centre of the screen when not loaded. Shrinks when charged but not loaded: Dual Crossbow, Exploding Crossbow, Feral Soul Crossbow, Firebolt Thrower, Imploding Crossbow, Shadow Crossbow, Soul Crossbow, Soul Hunter Crossbow, Spellbound Crossbow, The Slicer, Veiled Crossbow, Voidcaller

===

- OS: Windows
- Launcher: Default/Curseforge
- Mod Version: mcdw-5.0.4-1.19.jar
- Are you using a Modpack? No
