### ISSUE TITLE
Crash when I try to enchant any bow

### ISSUE THREAD

**Issue by Lahiox** [chronosacaria/MCDungeonsWeapons#154]
Crash when I try to enchant any bow in Anvil.
Version: mcdw-5.0.3-1.19
Attached is the text of the crash.
[crash-2022-08-30_22.55.30-client.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/9458628/crash-2022-08-30_22.55.30-client.txt)

Thanks.

**Comment by chronosacaria** [comment]
@Lahiox You just need to delete your configs in the mcdw folder and let them regenerate and it will fix the issue
