### ISSUE TITLE
Repairing Dungeon weapons crashes and deletes items

### ISSUE THREAD

**Issue by CharlieFoxtrotAlpha** [chronosacaria/MCDungeonsWeapons#155]
**Describe the bug**
The game crashes and I receive "array is null" error when trying to repair weapons on an anvil

**To Reproduce**
1. Take a damaged MC Dungeons Weapon
2. Insert weapon into the first slot
3. Place item intended to repair the weapon (iron, diamond, bow etc.)
4. Game crashes and see error

**Expected behavior**
Once I place the appropriate items, a display should show a repaired item.

**Screenshots**
![Screenshot (175)](https://user-images.githubusercontent.com/33388438/187889768-0fda15e9-388b-4ecf-b352-b9f073c7d024.png)

**Please complete the following information:**
 - OS: Windows
 - Launcher: Curseforge
 - Mod Version 5.0.3
 - Are you using a Modpack? No

**Comment by chronosacaria** [comment]
@CharlieFoxtrotAlpha Delete your configs in the mcdw folder and let them regenerate and that will solve your issue. :)
