### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Developer2704** [chronosacaria/MCDungeonsWeapons#156]
Animate the flail so it drags around and the chain moves just like in mc dungeons

**Comment by chronosacaria** [comment]
This is something that we'd love to do, but we would need some help in doing it. Do you have any ideas?

**Comment by Developer2704** [comment]
There are some open source rendering and animation apis on curseforge and GitHub that you could use to animate the flail and whip

**Comment by chronosacaria** [comment]
@Developer2704 Oh? That's awesome. Do you happen to know the names of any of them?

**Comment by Developer2704** [comment]
No, I don't.

**Comment by Developer2704** [comment]
Maybe you could try geckolib

**Comment by Developer2704** [comment]
Geckolib can animated items so it could work.

**Comment by chronosacaria** [comment]
Duplicate of #134
