### ISSUE TITLE
possibly further piglin woes

### ISSUE THREAD

**Issue by superon** [chronosacaria/MCDungeonsWeapons#16]
re: https://pastebin.com/1MedqZiS
i died in the nether and this crash occurred shortly after i collected the items i'd dropped on death.
possibly a coincidence, but also noted some trinket related items vanished...
reviewing video to see if i can supply any more or more precise info about this: https://www.twitch.tv/videos/851529445 at about 44 minutes in.

any other info that will help let me know if i can provide, you maybe able to tell i don't really have a clue though by listening to my blurb

**Comment by superon** [comment]
also i could whitelist you on this server of course if that helps, we won't know until it does i suppose :/

**Comment by chronosacaria** [comment]
So sorry that happened! And that it happened on stream. Something had something it shouldn't have. Your crash reports are one of the reasons that Mcdw is as stable as it is, so please keep sending them. I'll work on this tomorrow, though

**Comment by superon** [comment]
np, i realise the crashing will happen, this is why i'm testing and chat should know this, caught a few different issues today :)

**Comment by superon** [comment]
also i am noting there was an update after the version i used there, maybe coincidentally fixed?  more mashing later

**Comment by chronosacaria** [comment]
I think I fixed it with this update. The latest update that was released was to fix an issue with Chains :P

**Comment by chronosacaria** [comment]
Since the issue appears to be fixed, I am going to close this issue.
