### ISSUE TITLE
Combining Ambush III and Echo III

### ISSUE THREAD

**Issue by Choo-Choo-Oreo** [chronosacaria/MCDungeonsWeapons#160]
Combining Ambush III and Echo III enchantments like what the Swift Skriker has.

**To Reproduce Error**
Open the anvil and combine both the books that are of the same enchantments of what the Swift Skriker has and they fill to combine unlike what the Swift Skriker has.
**Expected behavior**
A combination of the enchantments books like on the Swift Skriker.
**Screenshots**
![image](https://user-images.githubusercontent.com/34584301/189253574-0be9eddd-03a2-4a61-89fa-d3158957756d.png)

 - OS: Windows
 - Launcher: Default
 - Mod Version: 5.0.3
 - Modpack: Yes (Private)

**Comment by chronosacaria** [comment]
Ah, that's a fair confusion. That combination is unique to the Swift Striker

**Comment by Kluzzio** [comment]
Because this is intentional design as the swift striker is the one exception to this incompatibility, this issue will be closed.
