### ISSUE TITLE
a couple of enchantment bugs

### ISSUE THREAD

**Issue by 444wa** [chronosacaria/MCDungeonsWeapons#161]
hey, so for some reason the Pain cycle enchantment is acting a little strange (i think). i know the enchantment is supposed to hurt the player as well, but only when they attack, right? for some reason whenever you get the pain cycle effect. it hurts the player nonetheless- like a slow poisoning.
also, i cannot seem to remove default enchantments off of any of the weapons. i really hope this isn't _supposed_ to be the case, for example, I can't seem to get rid of or improve the Dynamo I off of the Axeblade. 

Create a weapon with the pain cycle enchantment and just start attacking. you'll notice, with the effect on, and without you attacking anything, you will slowly start to lose health.

i know the enchantment is supposed to only harm the player during attacking, so maybe this is some sort of a bug.
i dont know if the inability to remove default enchantments was intentional, but i really hope it isn't. You should be able to remove default enchantments, that would seriously be so cool! I would like to be able to allow players in this mod pack I'm creating to be able to customize weapons and their enchantments as much as they want. Some of the default enchantments that won't go away, do clash with other sets of enchantments, and so on

![image](https://user-images.githubusercontent.com/104756144/189454733-6f0e5d6c-f013-4a10-8b59-21c16825612b.png)
![image](https://user-images.githubusercontent.com/104756144/189454745-12dd1bfd-c06b-456a-814d-628dc009e3d2.png)

i am also using the Dark enchanting table mod alongside this, which is compatible; But also not in some ways. Therefore i am unable to remove enchantments or improve the defaults using the table like you are supposed to. But also, even on a grindstone, they won't go away

**Comment by chronosacaria** [comment]
@444wa 
Re: Pain Cycle -- That is how it is supposed to function. If you build Pain Cycle and change your weapon so as not to use them, they will hurt you to the point of killing you. This is intentional design.

Re: Removing innate enchantments -- You are not supposed to be able to remove them. However, you can use the config settings to disable them in the first place. This is also intended functionality.

As both of the "issues" are actually due to intentional functionality, this issue shall be closed.

**Comment by 444wa** [comment]
thank you for the feedback. quick question, how would i go about disabling the default enchantments in the config? i am looking through them but i am not sure which to turn to false and such

**Comment by chronosacaria** [comment]
@444wa Sure thing! If you want to disable the innate enchantments, you need to look in the `mcdw_enchantment_settings_config.json5` file and there is a value called `ENABLE_INNATE_ENCHANTMENTS`. If you set that to `false`, it will remove the innate enchantments from items
