### ISSUE TITLE
Crash on game start

### ISSUE THREAD

**Issue by benio1394** [chronosacaria/MCDungeonsWeapons#162]
**Describe the bug**
https://pastebin.com/P8ZJk65e

 - OS: Windows
 - Launcher Deafult
 - Mod Version 5.0.4-1.18
 - Are you using a Modpack? Yes, my custom modpack

**Comment by Kluzzio** [comment]
Please update your clumps version. Then, let us know if that fixed it.

**Comment by benio1394** [comment]
I have the newest version for 1.18.2. But removing clumps helps

**Comment by Kluzzio** [comment]
For now, you can leave clumps out and you won't crash but I will try to find a solution as to why this is happening to you

**Comment by benio1394** [comment]
Thank you

**Comment by chronosacaria** [comment]
@benio1394 Are you using this version of Clumps: https://www.curseforge.com/minecraft/mc-mods/clumps/files/3913405

**Comment by chronosacaria** [comment]
Also, please, next time include the mod list at the end of your crashlog. I know that there can be a lot of information about your computer in there, but you can always delete that information. Having the list of mods, however, can be invaluable in situations like this

**Comment by chronosacaria** [comment]
As it has been a week since the initial message and the application of the `Awaiting Response` tag, since there has been no response, this issue shall be closed
