### ISSUE TITLE
Crash when putting looting book onto a Touched Blade through Anvil.

### ISSUE THREAD

**Issue by Gbergz** [chronosacaria/MCDungeonsWeapons#164]
**Describe the bug**
Game crashes when putting looting book onto a Touched Blade through Anvil.

**To Reproduce**
1. Get a Touched Blade
2. Get Looting Book
3. Put them together in an anvil. (I did shift click in the items into anvil, not sure if thats a requirement.)
4. Crash to desktop.

**Expected behavior**
Not to crash when putting them together in an anvil.

**Crash Report**
https://gist.github.com/Gbergz/09609585afb51229b54719cfc8884843

**Please complete the following information:**
 - OS: Windows 10, 11
 - Launcher. GDL, Curse, Polymorph, MMc.
 - MC 1.18.2
 - Fabric. - Loader: 0.14.9 - API: 0.58.0
 - Mod Version: mcdw-5.0.4
 - Are you using a Modpack? Yes, [TNP Limitless: Refabricated](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-refabricated)

**Additional context**
None.

**Comment by chronosacaria** [comment]
@Gbergz You just need to delete your configs for MCDW (in `mcdw`) and Enchant Giver (in `enchant_giver`) and it will solve your issue :)

**Comment by Gbergz** [comment]
Gotcha, thanks.

**Comment by chronosacaria** [comment]
No problem! Make sure, that if you're on a server, that the configs are deleted there as well
