### ISSUE TITLE
Weapons in Anvil crashes game 1.19 [mcdw-5.0.4]

### ISSUE THREAD

**Issue by EztraDev** [chronosacaria/MCDungeonsWeapons#165]
**Describe the bug**
(Watch video demo if i am unclear)
Weapons making game crash in Anvils with error: 
*
The game crashed whilst container click
Error: java.lang.NullPointerException: Cannot read the array length because "array" is null
*
Video demonstration: https://streamable.com/yrfak2
Whats in the video:
Showcase that weapons work in enchantment table.
Enchantment Giver works.
Other modded weapons (and vanilla) works in Anvil.
Weapons do not work in Anvil.

**To Reproduce**
1. Add weapon and add enchantment book. (alternatively another same weapon for "repair")
2. Crash and see error

**Expected behavior**
To be able to enchant the weapon by books.
Have worked with older version of mod. Previously used mcdw-4.4.0-1.19
and I think it work then. But I upgraded recently to get xp boosting enchantments to work properly.

**Screenshots**

**Please complete the following information:**
 - OS: Windows
 - Launcher CurseForge
 - Mod Version 5.0.4-1.19
 - Are you using a Modpack? Yes, Medieval MC v.5 (eg. the 1.19 version, NOT upgraded to 1.19.2)
 - Minecraft version is 1.19(.0)

**Comment by chronosacaria** [comment]
@EztraDev See https://github.com/chronosacaria/MCDungeonsWeapons/issues/164 for solution

Delete your configs on server and client
