### ISSUE TITLE
Crushing enchantments

### ISSUE THREAD

**Issue by ArtCrafter2999** [chronosacaria/MCDungeonsWeapons#167]
**Describe the bug**
When I have tried to enchant any weapon from this mod to any enchantment in anvil, the game is crush

**To Reproduce**
1. Go to an anvil
2. Place weapon in first slot
3. Place any enchantment book in second slot

**Expected behavior**
I expect to get the entchanted sword

**Screenshots**
![image](https://user-images.githubusercontent.com/92592800/190865796-c6cf7b73-0721-4167-b3dc-4e17713f66d1.png)
this is image how it looks before game is crush

**Please complete the following information:**
 - OS: Windows
 - Launcher: Default
 - Mod Version 5.0.4 - 1.18
 - Are you using a Modpack? there is 31 mods except this one

**Additional context**
This bug not work with enchantment table, and work only with weapon (armor enchants correctly)

**Comment by chronosacaria** [comment]
@ArtCrafter2999 
Отже, що вам потрібно зробити, це видалити деякі файли та дати їм відновитися. Вам потрібно буде видалити наступні файли в таких папках:
все в папці `mcdw`
все в папці `enchant_giver`
Це вирішить проблему, з якою ви зіткнулися.
