### ISSUE TITLE
[Bug Report]: enchant weapon with mending, crash game. 

### ISSUE THREAD

**Issue by amatorius36** [chronosacaria/MCDungeonsWeapons#169]
### Describe the bug; What happened?

Enchanting any weapon with mending crashes the game.

sorry, translation made in google 😭

[1.18.2  fabric 0.14.9]

### Expected Behavior

.

### Mod Version

mcdw-5.0.4-1.18.jar

### Minecraft Launcher

Other

### Operating System

Windows

**Comment by chronosacaria** [comment]
Hi @amatorius36 All you need to do is delete your configs in your `mcdw` and `enchant_giver` folders on the client and server and let them regenerate. That will resolve your issue :)

**Comment by chronosacaria** [comment]
Also, @amatorius36 Please use your native language, it is okay. I probably know it or know enough of it to help you :)

**Comment by amatorius36** [comment]
Muchas gracias por la rápida respuesta.
lo pruebo y comento si se soluciona

**Comment by amatorius36** [comment]
Efectivamente, se ha solucionado!
Muchas gracias
