### ISSUE TITLE
crash in Anvil

### ISSUE THREAD

**Issue by XimenesF** [chronosacaria/MCDungeonsWeapons#170]
### Describe the bug; What happened?

when you try to enchant any dungeons weapon with a enchanted book, the game crash and close.

### Expected Behavior

i really don't know nothing about codes and programation

### Mod Version

5.0.4

### Minecraft Launcher

Other

### Operating System

Windows

**Comment by Kluzzio** [comment]
Please delete your configs in the mcdw config folder to allow them to regenerate. This will solve the crash

**Comment by Kluzzio** [comment]
All you need to do is delete your configs in your mcdw and enchant_giver folders on the client and server and let them regenerate.
