### ISSUE TITLE
[Bug Report]: Bow of Lost Souls not Firing Multishot on a Server

### ISSUE THREAD

**Issue by Dxlls** [chronosacaria/MCDungeonsWeapons#171]
### Describe the bug; What happened?

Whenever i shoot the bow of lost souls on my 1.19.2 modded server it does not fire 3 arrow instead firing one

### Expected Behavior

The bow should fire 3 arrows

### Mod Version

5.0.4-1.19

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

Terracraft A Lightweight Overhual

**Comment by chronosacaria** [comment]
@Dxlls it will fire two arrows but only when there is an enemy nearby. Are you testing with enemies nearby?

**Comment by Dxlls** [comment]
Apologies, i just tested against an enemy and it worked fine. seems a bit odd that it only works if near an enemy but thanks you for the response and correction. have a good day/evening and thanks for the amazing mod

**Comment by chronosacaria** [comment]
No worries at all! The reason it does that is because the bow will only fire at a target rather than randomly. Thank you for your kind words :)
