### ISSUE TITLE
[Bug Report]: Anvil can't be used with Whispering Spear

### ISSUE THREAD

**Issue by DawZav** [chronosacaria/MCDungeonsWeapons#172]
### Describe the bug; What happened?

Putting a Whispering Spear in an anvil then placing another item (another whispering spear, enchanted books, etc.) freezes the screen, then exits the world and crashes the game. Anvil works fine with some other items, but not the Whispering Spear.

### Expected Behavior

The Whispering Spear and the second item are placed in an anvil, and the game _doesn't_ crash.

### Mod Version

5.0.2

### Minecraft Launcher

Vanilla

### Operating System

Windows

**Comment by chronosacaria** [comment]
@DawZav You need to regenerate the configs in your `enchant_giver` and `mcdw` folders. This is noted on the changelog for the 5.0.0 version, but any time you update from a version of a mod and the first number of that mod's versioning changes, you, almost certainly, if there are configs present, need to let them regenerate. This needs to be done on the server and client, if you are on a server

**Comment by DawZav** [comment]
Hey, thanks the for the response! I do need a bit of help though. What exactly do you mean "regenerate" them?
