### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by DemonMartin** [chronosacaria/MCDungeonsWeapons#173]
### Describe the bug; What happened?

When trying to enchant the "Frost Slayer" ( enchants: http://share.martin.tools/⁠‌‍‍‌‍‍⁠​​‌​ ) with "Lifesteal" (from [@Combat Enchantment](https://www.curseforge.com/minecraft/mc-mods/combat-enchantments), newest version) it causes the Game to crash. (Error is in additional context)

### Expected Behavior

Just enchant the item with the given enchantment.

### Mod Version

5.0.4

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

Fabrinaz (curseforge)

### Additional context

> Reported exception thrown!
> net.minecraft.class_148: Container click
> 	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4)
> 	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:497)
> 	at net.minecraft.client.Mouse.onMouseButton(Mouse:94)
> 	at net.minecraft.client.Mouse.method_22686(Mouse:165)
> 	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103)
> 	at net.minecraft.client.Mouse.method_22684(Mouse:165)
> 	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
> 	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133)
> 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
> 	at org.lwjgl.system.JNI.invokeV(Native Method)
> 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
> 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:197)
> 	at net.minecraft.client.util.Window.swapBuffers(Window:310)
> 	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1147)
> 	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
> 	at net.minecraft.client.main.Main.main(Main:236)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> Caused by: java.lang.NullPointerException: Cannot read the array length because "array" is null
> 	at java.util.Arrays.stream(Arrays.java:5428)
> 	at chronosacaria.mcdw.bases.McdwSword.canRepair(McdwSword.java:41)
> 	at net.minecraft.screen.AnvilScreenHandler.redirect$dhe000$hookUpdateResultCanRepair(AnvilScreenHandler:4043)
> 	at net.minecraft.screen.AnvilScreenHandler.updateResult(AnvilScreenHandler:141)
> 	at net.minecraft.screen.ForgingScreenHandler.onContentChanged(ForgingScreenHandler:80)
> 	at net.minecraft.class_4861$1.markDirty(class_4861.java:26)
> 	at net.minecraft.inventory.SimpleInventory.redirect$gda000$fabric_redirectMarkDirty(SimpleInventory:1043)
> 	at net.minecraft.inventory.SimpleInventory.setStack(SimpleInventory:140)
> 	at net.minecraft.screen.slot.Slot.setStack(Slot:61)
> 	at net.minecraft.screen.ScreenHandler.insertItem(ScreenHandler:657)
> 	at net.minecraft.screen.ForgingScreenHandler.transferSlot(ForgingScreenHandler:123)
> 	at net.minecraft.screen.ScreenHandler.internalOnSlotClick(ScreenHandler:396)
> 	at net.minecraft.screen.ScreenHandler.onSlotClick(ScreenHandler:295)
> 	at net.minecraft.client.network.ClientPlayerInteractionManager.clickSlot(ClientPlayerInteractionManager:417)
> 	at net.minecraft.client.gui.screen.ingame.HandledScreen.onMouseClick(HandledScreen:565)
> 	at net.minecraft.client.gui.screen.ingame.HandledScreen.mouseClicked(HandledScreen:361)
> 	at net.minecraft.client.gui.screen.ingame.AnvilScreen.mouseClicked(AnvilScreen:1093)
> 	at net.minecraft.client.Mouse.method_1611(Mouse:94)
> 	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:492)
> 	... 17 more
>

**Comment by chronosacaria** [comment]
@DemonMartin Delete your `mcdw` and `enchant_giver` configs. This happens when you update from a pre-5.0.0 version to a newer version

**Comment by DemonMartin** [comment]
Shouldn't you maybe add some kind of fix for that so it doesn't crash the game?

**Comment by DemonMartin** [comment]
maybe just output and error or something like that
