### ISSUE TITLE
Enchanting on weapons crashes user

### ISSUE THREAD

**Issue by ClubPZ** [chronosacaria/MCDungeonsWeapons#174]
### Describe the bug; What happened?

When enchanting any Mc Dungeons weapon it crashes the game. This only happens with Mc Dungeon weapons. The custom enchantments work on normal weapons but not the Mc Dungeons ones. I tried it on a server as well and only I crashed. I have a weapon with enchants that I made in the past so I know it used to work.

https://drive.google.com/file/d/1QBsa6-mXcaM35of-wquOcEcxVTvPH4vT/view?usp=sharing

### Expected Behavior

Enchant the weapon.

### Mod Version

mcdw-5.0.4-1.19

### Minecraft Launcher

CurseForge

### Operating System

Windows

**Comment by chronosacaria** [comment]
Delete your configs in the `mcdw` and `enchant_giver` folders
