### ISSUE TITLE
[Feature Request]: Void Strike not saying "Chance To" in the in game description.

### ISSUE THREAD

**Issue by Sethatee** [chronosacaria/MCDungeonsWeapons#176]
### Is your feature request related to a problem? Please describe.

I saw on the wiki that Void Strike has only a 15% chance to multiply the damage of the attack but the in-game description says, "Deal multiplicative damage based on level of enchantment." That caused me, and I'd assume others as well, to believe that it multiplied the damage of every attack. 

### Describe the solution you'd like

I would like the in-game enchantment description to say "Chance to deal multiplicative damage based on level of the enchantment."

**Comment by chronosacaria** [comment]
Lang files with problematic translations corrected
