### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by Veracis-Eclise** [chronosacaria/MCDungeonsWeapons#177]
### Describe the bug; What happened?

Conflicting enchantments such as Enigma Resonator and Void Strike can be applied together via the vanilla enchanting table. Enchanting a sponge striker in the enchantment table has a chance of applying void strike, among other enchants like sharpness and smite, onto the weapon.

![image](https://user-images.githubusercontent.com/118526661/202679442-4611fe18-fb0f-45bf-96e6-9df817c28a26.png)

### Expected Behavior

Void strike should not be able to be enchanted onto a weapon with enigma resonator. This issue can likely be replicated with similar items to the sponge striker, soul fist and void bow.

### Mod Version

5.0.4

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

DarkRPG

**Comment by Kluzzio** [comment]
This has already been fixed in dev and will be in the next release. Thank you for your patience and willingness to report this issue!
