### ISSUE TITLE
[Bug Report]: Range stat appears to not work for bows.

### ISSUE THREAD

**Issue by BluStryx8** [chronosacaria/MCDungeonsWeapons#178]
### Describe the bug; What happened?

While using bows, it seems that the range statistic does not work at all: all bows, once fully charged, will share the exact same range if they are part of the same bow class (regular bow, longbow, or shortbow)
For example, if you fire multiple arrows from an Ancient Bow with a range of 18, and a Shivering Bow with a range of 10, the arrows will all still land within the same general area.
This still persists even if you try to increase the range value to absurd values: a Power Bow with a range of 1000 still has the exact same range as an Ancient Bow with a range of -1. (so maybe the range stat isn't being read at all?)

This behavior only applies to the range stat of bows; crossbows are completely unaffected.

### Expected Behavior

Bows with different range stats should have different ranges.

### Mod Version

5.0.4

### Minecraft Launcher

CurseForge

### Operating System

Windows

**Comment by chronosacaria** [comment]
@BluStryx8 This occurs when you're updating from a pre-5.0.0 version of MCDW to a post-5.0.0 version of MCDW. To resolve this, delete the contents of both the `mcdw` and `enchant_giver` folders and let them regenerate. Also, make sure that you update Minecraft via the Vanilla Launcher as there was a bug in a previous Minecraft release that broke config reading. If this doesn't solve your issue, there is some kind of mod conflict

**Comment by BluStryx8** [comment]
Problem still persists when performed with a fresh CurseForge profile with just the mod installed, and no others (i.e. not updating from an older version of MCDW)
