### ISSUE TITLE
[Bug Report]: Bows reading off one stat

### ISSUE THREAD

**Issue by BluStryx8** [chronosacaria/MCDungeonsWeapons#179]
### Describe the bug; What happened?

Since the last one got closed almost immediately, I'm making another bug report because this definitely is *not* a version change issue: it's an issue with how range is being read. It seems to be defaulting to a specific bow's range stats:
- All regular bow range stats are determined by the `BOW_WINTERS_TOUCH` range stats
- All shortbows range stats are determined by the `BOW_SHORTBOW` range stats
- All longbow range stats are determined by the `BOW_RED_SNAKE` range stats
(Side note: these are also the internal ids of the bows that are alphabetically last in their bow categories)

And just to make sure, I deleted and let the configs regenerate, then modified only those bow's range stats, and sure enough, every bow was affected.

This only affects bows (and not crossbows), and draw speed is entirely unaffected.

### Expected Behavior

Every bow should be reading from their own ranged stat not from these specific three bows range stats.

### Mod Version

5.0.4

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

None. Fresh CurseForge profile with only the mod installed.

**Comment by chronosacaria** [comment]
@BluStryx8 Ah, okay. I see. Thanks for clarifying this issue

**Comment by Kluzzio** [comment]
We found the issue, was dumb (range was static lol). Is fixed in dev. Thanks so much for finding this!
