### ISSUE TITLE
[Bug Report]:All MC Dungeon Mods not loading on MC 1.19.2 Forge 43.1.57

### ISSUE THREAD

**Issue by zukatotokime** [chronosacaria/MCDungeonsWeapons#180]
### Describe the bug; What happened?

Mod has been added to mods folder, game starting normally but mod does not show up in mod list. Tried re-installing but no effect. All MC Dungeons Mods behave this way.

### Expected Behavior

It SHOULD just start and load into it

### Mod Version

5.0.4

### Minecraft Launcher

Other

### Operating System

Windows

**Comment by Kluzzio** [comment]
Please ensure that you are using the fabric loader and do not have a cracked client. Both of these are commonly not adhered to when this complaint is present. If you hop in the discord or can give more detail, that would be greatly appreciated.

**Comment by Kluzzio** [comment]
Just pointed out to me, that this is on a forge loader. ALL MCDX MODS are fabric exclusive. Consider using Dungeons Gear by infamous instead
