### ISSUE TITLE
[Feature Request]: Update the MCDungeons* series of Mods to Minecraft version 1.19.3?

### ISSUE THREAD

**Issue by lemonzest79** [chronosacaria/MCDungeonsWeapons#183]
### Is your feature request related to a problem? Please describe.

I am wondering if there is any progress porting these mods to minecraft version 1.19.3 as I'm currently using them on my 1.19.2 server and would like to upgrade.

### Describe the solution you'd like

It would be nice if the MCDungeons series of mods were ported to Minecraft version 1.19.3, thank you for your help

**Comment by chronosacaria** [comment]
@lemonzest79 This is definitely something that we are working on. However, we have been doing a charity event all month, which has taken priority over updating our mods. We also need to wait for dependencies to update before we can release a 1.19.3 version of MCDW

**Comment by chronosacaria** [comment]
@lemonzest79 I just wanted to update you on the progress of porting. MCDW is almost ready for 1.19.3. We're just finishing up some loose ends

**Comment by chronosacaria** [comment]
@lemonzest79 Just wanted to give you a heads up and follow up on previous posts. We are, more or less, done with the 1.19.3 port. We are in the stage of updating the other parts of MCDX and, during this time, cleaning up and unifying code across the projects

**Comment by chronosacaria** [comment]
@lemonzest79 MCDX have been released for 1.19.3
