### ISSUE TITLE
[Bug Report]: Cliennt crash on trying to shift click something in an occupied by MCDWeapon anvil

### ISSUE THREAD

**Issue by MaximilianPopov** [chronosacaria/MCDungeonsWeapons#185]
While having an item in the anvil and I try to shift-click lets say an enchantment book or anything else, it crashes my client, but the server still remains active.

**Comment by chronosacaria** [comment]
@DireDiamond I need a crash report

**Comment by mrdondemanz** [comment]
I have the same problem, even when i move an enchanting book into the anvil with one of these weapons it crashes, i can send the report if needed too.

**Comment by chronosacaria** [comment]
Yeah, if you can send a report. I think I know what the issue is, but I need to have a report to know for sure

**Comment by mrdondemanz** [comment]
[crash-2023-01-12_17.46.34-client.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/10404457/crash-2023-01-12_17.46.34-client.txt)
Tried adding a precision book into a heavy crossbow and the game crashed.

**Comment by Kluzzio** [comment]
Let your configs regenerate and will fix the issue. Delete your `enchant_giver` and `mcdw` configs on the server and the client
