### ISSUE TITLE
Lots of bow issues

### ISSUE THREAD

**Issue by ccuthbert001** [chronosacaria/MCDungeonsWeapons#186]
For me almost every bow and crossbow doesn't work, they either are a huge default bow, turn into a huge default bow, or don't show the loading animation.
![image](https://user-images.githubusercontent.com/109781983/214476335-aec48237-f40c-4705-9455-39d5bf1c51d1.png)
![image](https://user-images.githubusercontent.com/109781983/214476366-073f3694-867f-412a-8d13-af965de917f4.png)
![image](https://user-images.githubusercontent.com/109781983/214476409-98c4f310-a6de-4fc1-ad5a-29fdf5dced42.png)
![image](https://user-images.githubusercontent.com/109781983/214476494-dd3d37e6-7427-4aab-8611-f99042895d60.png)
![image](https://user-images.githubusercontent.com/109781983/214476515-a00b536e-a588-4c24-a695-8429ce745616.png)
![image](https://user-images.githubusercontent.com/109781983/214476698-87770721-b2eb-4bbf-97d8-78cfd1ff567b.png)
![image](https://user-images.githubusercontent.com/109781983/214476713-e639d25b-d764-4d65-ae18-226952c6679e.png)

**Comment by chronosacaria** [comment]
This is caused by a resource pack or mod conflict of some kind. Please provide a log so that I can see what is going on. This does not happen with just MCDW

**Comment by ccuthbert001** [comment]
Thank you! I removed all my resource packs and it worked. The only ones that still have issues are:
- Auto Crossbow
- Azure Seeker
- Baby Crossbow
- Burst Crossbow
- Corrupted Crossbow
- Cog Crossbow
- Harpoon Crossbow
- Harp Crossbow
- Nautical Crossbow
(They have the issue shown on the 3rd and 4th picture)
PS: How do I provide a log? The game doesn't crash from the issue.

**Comment by chronosacaria** [comment]
@ccuthbert001 That means there is a mod conflict. Are you using Dashloader? Have you tested MCDW alone? I know that there are some _placement_ issues, but no issues where the textures change like you're describing

**Comment by chronosacaria** [comment]
Due to lack of response and the inability to reproduce, this issue shall be closed
