### ISSUE TITLE
[Bug Report]:  cant find the mod for 1.18.2 on the curseforge app

### ISSUE THREAD

**Issue by NKT640** [chronosacaria/MCDungeonsWeapons#187]
### Describe the bug; What happened?

i can not find the mod when i search for it on the curseforge app. i tried to download via the curseforge button on the website and it said that the version was incompatible with my 1.18.2 modpack. and i would think that the mod is compatible since it says there are files for 1.18.2 on the curseforge website

### Expected Behavior

i expected to be able to download the mod without issue

### Mod Version

1.18.2

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

a custom profile

**Comment by chronosacaria** [comment]
@NKT640 Is your pack Forge or Fabric?

**Comment by NKT640** [comment]
the modpack is fabric

**Comment by NKT640** [comment]
> @NKT640 Is your pack Forge or Fabric?

the modpack is fabric

**Comment by chronosacaria** [comment]
So, you need to make sure that you're trying to download the correct version. If you click the button on the main page, it will download the latest version, which is only going to be 1.19.2. If you want the one for 1.18.2, you'll need to click under Files and select the version you want for the version of Minecraft you are running.
