### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by Autoded** [chronosacaria/MCDungeonsWeapons#188]
### Describe the bug; What happened?

Cannt enchant The Starless Night with Void Strike
![2023-01-29_08 19 38](https://user-images.githubusercontent.com/123847215/215298829-54e7f76a-f9a0-4c31-a81c-85bc85501496.png)
![2023-01-29_08 19 40](https://user-images.githubusercontent.com/123847215/215298831-e9f0ab33-1eea-4535-bf95-b2903be3abb4.png)
![2023-01-29_08 19 41](https://user-images.githubusercontent.com/123847215/215298833-5f2b4213-e7c9-4087-9e4b-6a49fdfc7ef9.png)

in earlier version on 1.18, if i not forget it work fine

### Expected Behavior

i want this bug fixed or is not a bug?

### Mod Version

5.0.4

### Minecraft Launcher

Vanilla

### Operating System

Windows

### Modpack

fabric custom mod

**Comment by chronosacaria** [comment]
It's not a bug

**Comment by Autoded** [comment]
so that enchant cant be mix?
