### ISSUE TITLE
[Bug Report]: Multishot enchantment does not seem to work with bows, as expected

### ISSUE THREAD

**Issue by csweet89** [chronosacaria/MCDungeonsWeapons#189]
### Describe the bug; What happened?

The Multishot enchantment on the Bow of Lost Souls does not shoot 3 arrows. It does not work on other bows either.

### Expected Behavior

3 arrows should shoot, similar to crossbows.

### Mod Version

1.19.2

### Minecraft Launcher

Vanilla

### Operating System

Windows

**Comment by chronosacaria** [comment]
This is the intended functionality. There is only one arrow that is fired when there is an appropriate target. Whilst it is the same name, this is because it is using some of the code from the Multishot enchantment from Vanilla

**Comment by csweet89** [comment]
Wait, then what does the enchantment do?  If it fires one arrow WITHOUT the enchantment and one arrow WITH it, then whats the point?

**Comment by csweet89** [comment]
To note, it doesnt fire 2 arrows either. It just fires one total.

I dont understand what it is supposed to add to the weapon.

**Comment by chronosacaria** [comment]
@csweet89 So the bow will only fire a secondary arrow if it sense a viable target. It is supposed to function as it the souls in the bow are firing the second arrow. Try testing in an environment where you are being attacked by multiple enemies. This has been confirmed to work in dev, single player and server environments

**Comment by csweet89** [comment]
> @csweet89 So the bow will only fire a secondary arrow if it sense a viable target.

Ah, I managed to get it to work, but its very inconsistent. It seems to only fire within a very narrow angle from the original shot, something like 15 degrees left or right.
It also does not seem to fire if the 2nd target is BEHIND the original target.
Third, it does not fire if the first shot misses.

It basically functions the same as a worse version of the Bonus Shot enchantment, since it doesn't fire at 100% strength either.



Lastly, it might be good to update the wiki description. It says it functions the same as vanilla, which, it definitely does not.
https://github.com/chronosacaria/MCDungeonsWeapons/wiki/Enchantment-Descriptions#multishot-

**Comment by csweet89** [comment]
I uploaded a video to show how it behaves for me. 
https://youtu.be/4grV2oGYSfs

At minimum, I think it would be good to change the wiki description and even the enchantment name since its misleading.

IMO, it should at least do 100% damage and fire more reliably.
