### ISSUE TITLE
upgrading default enchant

### ISSUE THREAD

**Issue by superon** [chronosacaria/MCDungeonsWeapons#19]
just wondering if stormlander "thundering I" should be able to be upgraded to "thundering II" via anvil and thundering I book for example.   seems to add and entirely different "thundering I" to the weapons enchants list instead..
not sure this isn't intended but seems odd https://imgur.com/9Dpwbpy

**Comment by chronosacaria** [comment]
I am working on fixing this. Once I have it working I'm going to be releasing an update. I just worked with someone to help me rewrite a lot of Mcdw and I just finished all of the enchantment stuff except for the combining. I am going to be working on that today, though :)

**Comment by chronosacaria** [comment]
This is now fixed in the latest version! :D
