### ISSUE TITLE
[Bug Report]: Order of config entries is unpredictable

### ISSUE THREAD

**Issue by Snownee** [chronosacaria/MCDungeonsWeapons#190]
### Describe the bug; What happened?

Using a LinkedHashMap in your config class can fix this, instead of a HashMap

![image](https://user-images.githubusercontent.com/16059084/219139561-6b1016da-fc84-43bf-9d25-9a5342d6d51d.png)

### Expected Behavior

Order of config entries is predictable

### Mod Version

v5.0.4-1.19

### Minecraft Launcher

CurseForge

### Operating System

Windows

**Comment by chronosacaria** [comment]
Thanks for pointing this out. This is something that is on our radar to implement after we finish cleaning things up and getting ready for 1.19.3 / 1.20
