### ISSUE TITLE
[Feature Request] Any plans for Forge?

### ISSUE THREAD

**Issue by FirdausCraft10** [chronosacaria/MCDungeonsWeapons#191]
### Is your feature request related to a problem? Please describe.

Nothing

### Describe the solution you'd like

I really like this mod from the texture and very cool design. But please port this mod for Forge

### Describe alternatives you've considered

Nothing

### Additional context

Nothing

**Comment by chronosacaria** [comment]
@FirdausCraft10 Thank you for your kind words. At this time, there is an agreement in place with Infamous Misadventures, the makers of Dungeons Gear, that states that we will stick with Fabric and they will stick with Forge. However, we are in conversations about possibly helping translate each other's works to the other Mod Loader. This does not mean that we will be porting to Forge; just that there are conversations happening.

Please join the Timefall Development Discord for any updates.
[https://www.discord.gg/meBurdvYWH](https://www.discord.gg/meBurdvYWH)

**Comment by FirdausCraft10** [comment]
Dungeon Gears criticaly crash with Optifine, So i can't use any dungeons mod exept, "Dunegons Weaponry" But however. Thank you for the information!

**Comment by chronosacaria** [comment]
No problem, mate! We'll keep this issue open in case there are any changes :)

**Comment by chronosacaria** [comment]
This has been taken care of by [@Sinytra/Connector](https://github.com/Sinytra/Connector)
