### ISSUE TITLE
[Bug Report]: Inflicting crafting recipe to another/different mod

### ISSUE THREAD

**Issue by Gexi69** [chronosacaria/MCDungeonsWeapons#192]
### Describe the bug; What happened?

I have another mod installed named "Croptopia". One of the weapons (Dagger) has the same recipe as their butcher's knife. I will also be reporting this to the other mod creator in case one of you can update me about the issue.

### Expected Behavior

To craft the dagger. 

### Mod Version

5.0.4

### Minecraft Launcher

Other

### Operating System

Windows

### Modpack

N/A

### Additional context

![image](https://user-images.githubusercontent.com/125441823/221367664-1639fef0-d3ec-4cc7-9e72-b21e26d5632a.png)
![image](https://user-images.githubusercontent.com/125441823/221367674-5be4a08c-128c-4602-ba49-24412d0ef0fa.png)

**Comment by chronosacaria** [comment]
This can be resolved by installing polymorph. Unfortunately, when there are a bunch of mods that add similar things, there are bound to be overlapping recipes

**Comment by chronosacaria** [comment]
Here is a link to the Fabric version of Polymorph: [https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric](https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric)

**Comment by Gexi69** [comment]
Thanks! Will check it out
