### ISSUE TITLE
[Bug Report]: Server crashign on trying to create an item

### ISSUE THREAD

**Issue by Zunwolf1896** [chronosacaria/MCDungeonsWeapons#194]
### Describe the bug; What happened?

The server crashed, I was not online, I got spam messages in the discord with players askign why the server crashed. A mod restarted the server, and it instantly crashed again. The server did not properly close, we had to force shut it down. 

I had a read through the messages and saw it mentining both

Unknown enchantment 'minecraft:'

and later:

mcdw permit Innate Enchantments To Be Enchanted But No tWith Conflicts

### Expected Behavior

The server not to crash?

### Mod Version

5.0.5

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

WolfQueen's Origins V5

### Additional context

Heres a list of the crashes that were caused

[crash-2023-03-12_00.13.19-server.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/10951530/crash-2023-03-12_00.13.19-server.txt)
[crash-2023-03-12_00.21.51-server.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/10951531/crash-2023-03-12_00.21.51-server.txt)
[crash-2023-03-12_00.30.33-server.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/10951532/crash-2023-03-12_00.30.33-server.txt)
[crash-2023-03-12_00.35.29-server.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/10951533/crash-2023-03-12_00.35.29-server.txt)
[crash-2023-03-12_01.04.33-server.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/10951534/crash-2023-03-12_01.04.33-server.txt)
[crash-2023-03-12_01.10.54-server.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/10951535/crash-2023-03-12_01.10.54-server.txt)
[crash-2023-03-12_08.22.07-server.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/10951536/crash-2023-03-12_08.22.07-server.txt)
[crash-2023-03-12_17.08.45-server.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/10951537/crash-2023-03-12_17.08.45-server.txt)
[crash-2023-03-12_17.09.46-server.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/10951538/crash-2023-03-12_17.09.46-server.txt)
[crash-2023-03-11_23.46.51-server.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/10951539/crash-2023-03-11_23.46.51-server.txt)
[crash-2023-03-11_23.49.53-server.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/10951540/crash-2023-03-11_23.49.53-server.txt)
[crash-2023-03-11_23.53.52-server.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/10951541/crash-2023-03-11_23.53.52-server.txt)
[crash-2023-03-11_23.57.30-server.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/10951542/crash-2023-03-11_23.57.30-server.txt)
[crash-2023-03-12_00.02.49-server.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/10951543/crash-2023-03-12_00.02.49-server.txt)

**Comment by Kluzzio** [comment]
Update to newest version should stop throwing this error
