### ISSUE TITLE
[Bug Report]:  Enchantment Mixin Mixup

### ISSUE THREAD

**Issue by cleannrooster** [chronosacaria/MCDungeonsWeapons#197]
### Describe the bug; What happened?

MC Dungeons Weapons enchantments not applying on weapons, instead all possible enchantments are being allowed on every weapon in the game

### Expected Behavior

Weapons only being able to be enchanted by fitting enchantments/MC Dungeons Weapons enchantments enchantable on weapons

### Mod Version

5.0.7-1.19

### Minecraft Launcher

Other

### Operating System

Windows

### Modpack

Custom Modpack

### Additional context

Line 44 of EnchantmentMixin.java

**Comment by chronosacaria** [comment]
@cleannrooster We were unable to reproduce this. I am wondering if you are testing whilst in creative mode. If you are, you can apply any enchantment to anything. This is a vanilla mechanic.
