### ISSUE TITLE
[Bug Report]: Spear is only getting Unbreaking from enchanting

### ISSUE THREAD

**Issue by V7I0SeventhSector** [chronosacaria/MCDungeonsWeapons#199]
### Describe the bug; What happened?

when ever i try and enchant any of the spears using a basic enchanter, i will only ever get Unbreaking, I've done some testing and this happens even when its the only mod in the pack. 

### Expected Behavior

it should give set/random enchants based on the weapons available enchants 

### Mod Version

5.0.4-1.19

### Minecraft Launcher

Vanilla

### Operating System

Windows

**Comment by Kluzzio** [comment]
Additional Context: We know about this issue and are trying to find a good solution. This is also the case with the whips because the two weapon types use a custom weapon base.

**Comment by chronosacaria** [comment]
Fixed in https://github.com/chronosacaria/MCDungeonsWeapons/commit/acaafd35d37ec4410ae17caa56b912cd37f1ea1f
