### ISSUE TITLE
special arrows with bows and crossbows now don't work

### ISSUE THREAD

**Issue by superon** [chronosacaria/MCDungeonsWeapons#20]
just that, in the new version mcdw-2.4.8 the draw back animation works but the arrows don't fire :(

**Comment by chronosacaria** [comment]
but it worked in the previous versions, right?

**Comment by chronosacaria** [comment]
Yeah, I cannot reproduce this. Do you have any other mod installed that might be affecting bows and crossbows?

**Comment by superon** [comment]
ahh, i'll do some testing

**Comment by superon** [comment]
thought i'd found it was a conflict after a while but now the problem seems to have simply vanished :/

**Comment by superon** [comment]
happens in one very specific version of my modpack, as yet i've still no clue but thought i'd post here incase it makes sense https://pastebin.com/qRa7gzEY

**Comment by chronosacaria** [comment]
What was the mod that set it off? I know what the error means

**Comment by superon** [comment]
idk, pulled apart and stuck the modpack back together again several times and still no clue where it came from
