### ISSUE TITLE
[Bug Report]: Sun's Grace Not Detectable By Commands

### ISSUE THREAD

**Issue by MilkyMilkityMilk** [chronosacaria/MCDungeonsWeapons#200]
### Describe the bug; What happened?

I was trying to make a ritual for a boss in my server and it called for a Sun's Grace however no matter what i try the commands seem to outright ignore it

### Expected Behavior

instead of selecting the item with the /execute command it is not interacting

### Mod Version

most recent

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

Stratosphere Content

### Additional context

the only mod that interacts with it in the pack is enchancement,

**Comment by chronosacaria** [comment]
@MilkyMilkityMilk We need more information about what you're trying to do. It sounds like you might be trying to reference the Sun's Grace improperly. When using the `/execute` command, I was able to access it without issue (see attached image). Also, in the future, please put the actual version that you're using for the Mod Version
![image](https://user-images.githubusercontent.com/67794130/231817566-baaddd64-ffeb-4771-b7c9-82fe880acc3d.png)

**Comment by chronosacaria** [comment]
This issue shall be closed due to lack of response from OP
