### ISSUE TITLE
[Bug Report]: Enchantment incompatability buypass on weapons with integrated enchantments

### ISSUE THREAD

**Issue by CyraLX** [chronosacaria/MCDungeonsWeapons#201]
### Describe the bug; What happened?

Enchantments that come default on weapons, which also can be upgraded to higher levels then 1 using books, do not have incompatibilities with enchantments than they should be normally.
For example `Call of the Void` bow has `Fuse Shot I` and `Void Shot I`. Although it has Void Shot it is still compatible with enchantments such as Power (Adding Void Shot to a Power Bow removes Void Shot, but not here).

### Expected Behavior

Weapon integrated enchantments should retain incompatibilities

### Mod Version

5.0.7

### Minecraft Launcher

Vanilla

### Operating System

Linux

### Modpack

Custom

### Additional context

Tested on Minecraft 1.19.2 Fabric Loader 0.14.19

**Comment by Kluzzio** [comment]
Neither of those enchantments were made incompatible with Power so this is expected behavior
