### ISSUE TITLE
[Bug Report]: Multishot does not function on bows

### ISSUE THREAD

**Issue by SomeFellaUnknown** [chronosacaria/MCDungeonsWeapons#206]
### Describe the bug; What happened?

bows cannot be enchanted with multishot (unlike what the wiki says), and the Bow of Lost Souls, which comes preenchanted with it, does not shoot multiple arrows.

### Expected Behavior

according to the wiki, multishot should affect bows. The fact that an item comes prenchanted with something means it prolly should work with that.

### Mod Version

6.0.4

### Minecraft Launcher

Other

### Operating System

Linux

**Comment by chronosacaria** [comment]
Fixed with this commit to the Wiki: https://github.com/chronosacaria/MCDungeonsWeapons/wiki/Enchantment-Descriptions/abadd98bef18756dc84095a8c1cd333e3a068291
