### ISSUE TITLE
adding enchant - enhancement/suggestion

### ISSUE THREAD

**Issue by superon** [chronosacaria/MCDungeonsWeapons#21]
<3 the new ability to add enchants via config, that right there brought new life to some old items.

wondering if this could be extended so it can be applied to item in hand?

hoping for this for a quite specific example:
my modpack has a book given to the player which explains a few oddities about gameplay and general mechanics within, this is a minecraft:written_book
as things are i can add an enchant to that (the idea being to add a soulbound enchant so that when players die without reading it {a regular occurrence no matter how many times i advise against not reading it before dying} the book remains in the inventory..  finally no excuse for not knowing some basic things).

to be fair i've not tried to shoehorn soulbound onto this book with the config supplied but i am imagining some difficulty doing so

**Comment by chronosacaria** [comment]
This is beyond the scope of MCDW. You could soulbound the book, but any written book would be affected. 

However, it sounds like you might want to consider making a patchouli book for your pack. 

https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric

**Comment by superon** [comment]
i tried and failed at that, np though i'm quite happy to make all written books souldbound 👍
