### ISSUE TITLE
[Bug Report]: "The End" is incompatible with sharpness or void strikr

### ISSUE THREAD

**Issue by RazzorWind** [chronosacaria/MCDungeonsWeapons#210]
### Describe the bug; What happened?

Using a sharpness book or a void strike book on The End does not work, even in creative mode even though you can enchant the sword directly in the enchanting table.

### Expected Behavior

Should be compatible with the list of compatible enchants.

### Mod Version

5.0.4-1.18

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

https://www.curseforge.com/minecraft/modpacks/ralseisrougelikerpg

**Comment by chronosacaria** [comment]
1.18 is no longer supported. Please update to the latest version
