### ISSUE TITLE
burst bowstring marks ENABLE_RANDOM_SELECTION as false twice 

### ISSUE THREAD

**Issue by SomeFellaUnknown** [chronosacaria/MCDungeonsWeapons#211]
in McdwEnchantmentsConfig.java, burst bowstring gets ENABLE_RANDOM_SELECTION set to false twice, rather than having both ENABLE_RANDOM_SELECTION and ENABLE_VILLAGER_TRADING set to false like how Dynamo and Shared Pain works.

![Screenshot from 2023-04-30 15-05-52](https://user-images.githubusercontent.com/100487467/235357288-dd19cd2c-79c5-47ba-beb0-cd89d6a1ccd6.png)

**Comment by chronosacaria** [comment]
Whoops! Thanks for catching that!
