### ISSUE TITLE
[Optifabric optifine]: 

### ISSUE THREAD

**Issue by Sosamonster** [chronosacaria/MCDungeonsWeapons#212]
### Describe the bug; What happened?

Issues while atempting to start the game when mcdw is installed in minecraft with optifine and optifabric, the game just crash, do any one else have this problem? or know any solution to this?

### Expected Behavior

The game should work well with optifabric and optifine if mcdw is installed as well

### Mod Version

1.19.2 fabric

### Minecraft Launcher

Other

### Operating System

Windows

**Comment by chronosacaria** [comment]
Optifine is a mess of a mod and Optifabric enables the use of such a mod. It will _never_ be supported intentionally. If you wish to use shaders or CIT Resource Packs, consider using Sodium, Iris, Indium and CIT Resewn to accomplish the same thing

**Comment by Sosamonster** [comment]
same issue with sodium, the game crashes

**Comment by chronosacaria** [comment]
Need a crash report to see what you're doing wrong. I know that it works with Sodium without issue as that is what I use
