### ISSUE TITLE
[Bug Report]: Crash on Client start with 1.19.2 and mcdw 5.0.10-1.19

### ISSUE THREAD

**Issue by suerion** [chronosacaria/MCDungeonsWeapons#218]
### Describe the bug; What happened?

Hey, my Client Crash with this Crashlog on 5.0.10, with 5.0.8 it works fine.

I had Updated only MCDW

[2023-05-17-1.log](https://github.com/chronosacaria/MCDungeonsWeapons/files/11499662/2023-05-17-1.log)

### Expected Behavior

Load Without Problem

### Mod Version

5.0.10

### Minecraft Launcher

CurseForge

### Operating System

Windows

**Comment by suerion** [comment]
I think it is a duplicate from #217

**Comment by chronosacaria** [comment]
@suerion Yeah, it is. We're working on a solution, but in the meantime, follow the steps in this reply: https://github.com/chronosacaria/MCDungeonsWeapons/issues/217#issuecomment-1550517397. I'm gonna close this issue as a duplicate, though. If you run into any issues, please reply in https://github.com/chronosacaria/MCDungeonsWeapons/issues/217. Thanks!
