### ISSUE TITLE
[Feature Request]: Enchantments exclusive to weapon

### ISSUE THREAD

**Issue by slammaja** [chronosacaria/MCDungeonsWeapons#219]
### Is your feature request related to a problem? Please describe.

Hi, 
weapons don't feel that special especially since you can get higher level enchantment on any weapon.

### Describe the solution you'd like

Would it be possible to add config option to have enchantments generated exclusively on MCD weapon and remove enchantments from ench table pool to make them unobtainable via regular enchanting? 

### Describe alternatives you've considered

And is it somehow feasible to have weapons with  same enchantment spawned/created with different levels of enchantment? For example void strike I on weapon A and void strike III on weapon B.

### Additional context

Maybe add option to make weapons just lootable and not craftable? 

Thank you for reading, I know it is a lot to ask. If none of those ideas is doable still you have done great job and I like your mod.

**Comment by chronosacaria** [comment]
@slammaja You can actually do this with the built in EnchantGiver config. It is in the enchantgiver directory
