### ISSUE TITLE
[Bug Report]: Game crashes when right clicking blocks with swords.

### ISSUE THREAD

**Issue by TimeIsTooSandy** [chronosacaria/MCDungeonsWeapons#221]
### Describe the bug; What happened?

Game completely crashes when right clicking blocks with swords, crash report attached.

Running Quilt v0.18.10-1.19.2, apparently the Quilt API is missing parity from the Fabric API that is necessary to prevent this crash.

[crash-2023-06-05_16.16.41-client.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/11659358/crash-2023-06-05_16.16.41-client.txt)

### Expected Behavior

The game should just continue running, or, in the event that you're clicking a log, strip the bark from the log.

### Mod Version

5.0.11

### Minecraft Launcher

Vanilla

### Operating System

Windows

### Modpack

N/A

**Comment by fzzyhmstrs** [comment]
Relevant discord talk: https://discord.com/channels/808825402566377532/1115419950568439908
