### ISSUE TITLE
[Bug Report]: wild rage cannot make illagers fight other illagers

### ISSUE THREAD

**Issue by SomeFellaUnknown** [chronosacaria/MCDungeonsWeapons#226]
### Describe the bug; What happened?

while under the effects of wild rage, illagers will attack non-illager mobs as expected, but they will still refuse to attack other illagers

### Expected Behavior

you'd expect illagers to attack everything, including other illagers

### Mod Version

6.0.4

### Minecraft Launcher

Other

### Operating System

Windows

**Comment by chronosacaria** [comment]
This is intended
