### ISSUE TITLE
[Bug Report]: Guarding Strike inconsistent with similar enchants

### ISSUE THREAD

**Issue by SomeFellaUnknown** [chronosacaria/MCDungeonsWeapons#227]
### Describe the bug; What happened?

Rampaging and Rushdown each have an 10% configurable chance to trigger, and will hide the effect icon and particles after triggering.

Guarding strike is supposed to be an similar enchantment that applies an temporary status effect on user after killing something, but it always triggers rather than having an configurable chance to trigger, and neither particles nor effect icon are hidden.

### Expected Behavior

for Guarding Strike to behave like it's sibling enchantments

### Mod Version

8.0.0

### Minecraft Launcher

Vanilla

### Operating System

Windows

### Modpack

none, just mcdw, mcda and required dependencies

**Comment by chronosacaria** [comment]
Since this is an enchantment that provides a defence boost, the logic for making this visual is for accessibility. Other enchantments that are on chance have other indicators, but since this one doesn't have any kind of visual indication, we opted for this. As such, it functions as intended.
