### ISSUE TITLE
Mood Dagger + Eldritch Mobs mod = EXP bomb

### ISSUE THREAD

**Issue by tealtoxic** [chronosacaria/MCDungeonsWeapons#23]
im no expert detective but hear me out,

testing out a friend;s modpack and everytime eldritch miniboss get killed by the moon dagger, it will drops tons of exp and eventually crashed the server.

i think theres something wrong with "Enigma Resonator – Deals damage relative to the amount of XP that the user has ".

instead of the more exp = the more damage dealt, it became exp bomb. 

can you please have a look :) tq

**Comment by chronosacaria** [comment]
Could you send me the crash report? I think I know what is wrong, but the report would help a lot

**Comment by tealtoxic** [comment]
i will ask my friend for it and send it to you.
