### ISSUE TITLE
[Bug Report]: Guarding Strike applicable to anvils

### ISSUE THREAD

**Issue by palapapa** [chronosacaria/MCDungeonsWeapons#232]
### Describe the bug; What happened?

If you have a mod that allows enchantment on anvils, for example, Zenith, then Guarding Strike appears as a possible enchantment for anvils. Other sword enchantments don't have this issue.

### Expected Behavior

Guarding Strike shouldn't be applicable to anvils.

### Mod Version

5.0.13

### Minecraft Launcher

Vanilla

### Operating System

Windows

**Comment by chronosacaria** [comment]
@palapapa Could you do me a favour and load up a world, enchant an anvil with Guarding Strike, immediately log out and then send me your `latest.log` file, please? This will let me see how and why this is able to happen without having to try to figure out your mod configurations

**Comment by palapapa** [comment]
Alright, but in the meantime, could I ask whether this mod provides the descriptions of enchantments? Because I found the description of Refreshment to be wrong. It should just be "upon kill", without "melee weapon". If not, then this is a problem with Enchantment ToolTips and I will report this issue there. If yes, then I can make another issue for this here.
![2023-07-12_05 16 18](https://github.com/chronosacaria/MCDungeonsWeapons/assets/61058728/5875838f-9a58-43a4-a2f1-bb7720d6172c)

**Comment by palapapa** [comment]
Here you go. I tried a few times before I got Guarding Strike. On the try I got it I immediately quit. The world was created beforehand, then I restarted the game and did this test, if that's relevant.
[latest.log](https://github.com/chronosacaria/MCDungeonsWeapons/files/12021707/latest.log)

**Comment by chronosacaria** [comment]
@palapapa Oh wow, I didn't realise we missed that. That is a carry over from when we had different enchantments for shot variants. Please open an issue here and I'll fix that. Thanks!
