### ISSUE TITLE
[Bug Report]: Broken Sawblade can be enchanted with unbreaking (this should not be possible)

### ISSUE THREAD

**Issue by SomeFellaUnknown** [chronosacaria/MCDungeonsWeapons#237]
### Describe the bug; What happened?

you are not prevented from enchanting an broken sawblade with unbreaking in an enchanting table, and you are not prevented from applying unbreaking to an broken sawblade or mechanized sawblade via an anvil. I cannot for the life of me find a single situation where the intended behaviour for the broken sawblade is applicable

### Expected Behavior

the changelog claims that these items are meant to be incompatible with unbreaking, and the code seems to imply they are meant to be incompatible with unbreaking

### Mod Version

8.0.3

### Minecraft Launcher

Vanilla

### Operating System

Windows

### Modpack

mcdw + required dependencies, 1.20.1

### Additional context

also did not happen in 8.0.0

**Comment by chronosacaria** [comment]
@SomeFellaUnknown Thanks for catching this! I wonder if something changed from when I did the testing and got this working inDev and when it was released. I'll look into this on Monday! :)
