### ISSUE TITLE
[Bug Report]: enchanted Broken sawblades (and other weapons) can be enchanted with enchanting table more than once

### ISSUE THREAD

**Issue by SomeFellaUnknown** [chronosacaria/MCDungeonsWeapons#238]
### Describe the bug; What happened?

if an mcdx item that has no innate enchantment (such as a broken sawblade, spear or mace) is put inside of an enchanting table and you give it an enchantment, the buttons that apply the enchantments do not go away as long as you don't remove the item from the enchantment table, allowing you to press more than one of the buttons or press one of the buttons multiple times; this also allows you to apply multiple instances of the same enchantment on an item.

![image](https://github.com/chronosacaria/MCDungeonsWeapons/assets/100487467/cd739681-0799-4df8-9067-1acb3bc3fe07)

![image](https://github.com/chronosacaria/MCDungeonsWeapons/assets/100487467/99ba5d7a-f0cd-4d47-b6ef-362143e2f689)

### Expected Behavior

uuuuuuh well i feel this one goes without saying, an enchanting table should only work once

### Mod Version

8.0.3

### Minecraft Launcher

Vanilla

### Operating System

Windows

### Modpack

mcdx + required dependencies

**Comment by chronosacaria** [comment]
@SomeFellaUnknown Thanks for catching this. I am not sure why it is duplicating, but I'll dig into this on Monday
