### ISSUE TITLE
Minor recipe issue

### ISSUE THREAD

**Issue by BrekiTomasson** [chronosacaria/MCDungeonsWeapons#24]
Nothing major, just wanted to highlight a small problem with one of your recipes. I'm using v2.5.0. Getting this on boot:

```
[15:38:05] [main/ERROR]: Parsing error loading recipe mcdw:pick_howling_pick
com.google.gson.JsonSyntaxException: Key defines symbols that aren't used in pattern: [/]
```

Looks like you're defining `minecraft:stick` as an ingredient in the recipe in `/src/main/resources/data/mcdw/recipes/pick_howling_pick.json` but not using it in the actual grid recipe.

**Comment by chronosacaria** [comment]
Whoops, thanks for catching that! :)
