### ISSUE TITLE
[Question]: How to create custom crossbows?

### ISSUE THREAD

**Issue by swapmasterx** [chronosacaria/MCDungeonsWeapons#242]
### Describe the solution you'd like

Don't know where else to reach out so if this gets a takedown with a pointer to a better spot I understand. 
Been trying to create my own custom crossbow type weapons for my own mod but info out there is extremely spotty or is something to do with MCcreator. Saw your mod had custom bow types so I though to ask how you did it. I'm new to coding so I might be a bit slow on the uptake but if you have a good set up or even a in-action example I'd be extremely grateful.

**Comment by chronosacaria** [comment]
@swapmasterx this is, in no way, shape or form an appropriate place for this. Come to the Discord and ask for help there
