### ISSUE TITLE
[Bug Report]: Incompatibility with Penkui 

### ISSUE THREAD

**Issue by Jafooleryy** [chronosacaria/MCDungeonsWeapons#243]
### Describe the bug; What happened?

Crashes when both mods are added.

### Expected Behavior

Should launch with no issues

### Mod Version

8.0.3

### Minecraft Launcher

Vanilla

### Operating System

Windows

### Additional context

Using the Penkui mod combined with MC Dungeons Weapons would result in a crash. These mods worked correctly on 1.19, what would be the issue?

**Comment by chronosacaria** [comment]
@Jafoolery Without a log or crash report we cannot help you

**Comment by chronosacaria** [comment]
Due to the lack of a log being produced, this issue shall be closed
