### ISSUE TITLE
[Bug Report]: Can't apply Void Strike to Sharpness (Fabric 1.20)

### ISSUE THREAD

**Issue by logankir** [chronosacaria/MCDungeonsWeapons#246]
### Describe the bug; What happened?

With either /enchant or anvils, void strike is restricted on swords or axes with sharpness.

### Expected Behavior

In previous versions (1.19) this was normal so I think this may be a bug for 1.20.

### Mod Version

8.0.3

### Minecraft Launcher

Vanilla

### Operating System

Windows

### Modpack

N/A

**Comment by chronosacaria** [comment]
@logankir The ability to apply Sharpness and Void Strike on the same weapon was actually the bug and was present in previous versions of MCDW. In 1.20.x and forward, this was corrected. That being said, if you want to be able to apply Sharpness and Void Strike to the same weapon, enable `OP_MIXING` in the config

**Comment by logankir** [comment]
@chronosacaria Thank you! I had already tried enabling OP_MIXING in config but it did not work as expected. Removing the mod "Universal Enchants" allowed for them to be paired together now.

**Comment by chronosacaria** [comment]
Thanks for mentioning the issue between MCDW and Universal Enchants. We weren't aware of that. We can look into if we can mitigate that issue
