### ISSUE TITLE
[Bug Report]: MCDW crashes while using Enchancements

### ISSUE THREAD

**Issue by Snowbirb** [chronosacaria/MCDungeonsWeapons#248]
### Describe the bug; What happened?

Enchancements is an enchantment overhaul and if enchantments and in short they change a lot. However, when loading into a world with both of these mods when opening the inventory. The game crashes

### Expected Behavior

The game does not crash and the enchantments are normal.

### Mod Version

8.0.3

### Minecraft Launcher

Vanilla

### Operating System

Windows

### Modpack

Custom modpack with MCDW and Enchancements installed

### Additional context

This custom modpack is very very large and I'm at the point where I'm fixing all the issues. So there is a good chance that this could be multiple mods clashing. I still hope to see if this can be fixed in the future.

**Comment by chronosacaria** [comment]
@Snowbirb Could you provide the crashlog, please? Without it there really isn't much we can do

**Comment by chronosacaria** [comment]
This issue is being closed due to lack of a response
