### ISSUE TITLE
[Bug Report]: Soul Devourer enchantment will not combine with chestplate or any armor (including armor from the mod)

### ISSUE THREAD

**Issue by Iamaturd** [chronosacaria/MCDungeonsWeapons#249]
### Describe the bug; What happened?

I made my own custom modpack and for some reason Soul Devourer simply wont combine with any of my armor pieces. It works just fine with my sword but it will not combine with armor. Mod menu says I am on version 2.4.4 and Curseforge says I am on version 5.0.13-1.19. I will add a list of all my mods.
[Diahhrea Blasting-1.zip](https://github.com/chronosacaria/MCDungeonsWeapons/files/13172241/Diahhrea.Blasting-1.zip)

### Expected Behavior

Soul devourer should be on my armor

### Mod Version

5.0.13

### Minecraft Launcher

Vanilla

### Operating System

Windows

### Modpack

Custom

**Comment by chronosacaria** [comment]
It is a weapon enchantment. This is intended

**Comment by Iamaturd** [comment]
my bad I confused this with bag of souls
