### ISSUE TITLE
[Bug Report]: ranged weapons enchantments dont work in ranged, only when you use the ranged weapon as a melee weapon (forge + connector + ffapi)

### ISSUE THREAD

**Issue by Scizith** [chronosacaria/MCDungeonsWeapons#252]
### Describe the bug; What happened?

As the title says, cant get bow enchants to work when firing, only when using as a melee weapon. using connector #26 along with ffapi and connector extras. 

### Expected Behavior

bow enchantments should proc effect when arrow hits, not when using the bow as a melee weapon.

### Mod Version

8.1.0

### Minecraft Launcher

Vanilla

### Operating System

Windows

**Comment by chronosacaria** [comment]
@Scizith I forgot to mention that we need the version of Forge that you're using. Also are you using LexForge or NeoForge? That way we can test with the same versions

**Comment by Scizith** [comment]
server is forge 47.2.0, my client is 47.2.1. I believe I am using lexforge technically

**Comment by chronosacaria** [comment]
Update: This turns out to not actually be the case. There are certain enchantments that were missed when adding to the ppe arguments. This will be fixed in the next release
