### ISSUE TITLE
forge mcdw does not want to load

### ISSUE THREAD

**Issue by VilligerKing** [chronosacaria/MCDungeonsWeapons#254]
### Describe the bug; What happened?

mcdw forge does not want to load on forge

### Expected Behavior

loadng, but loadnt

### Mod Version

9.0.0

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

custom

### Additional context

log:

[latest.log](https://github.com/chronosacaria/MCDungeonsWeapons/files/13749221/latest.log)

crash report:
[crash-2023-12-22_02.54.05-client.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/13749223/crash-2023-12-22_02.54.05-client.txt)

**Comment by chronosacaria** [comment]
@VilligerKing Do not provide a zip. Provide an actual list of mods, please. It doesn't appear that you have all of the required dependencies that are listed on the mod pages, however. Make sure you have all of the requirements

**Comment by VilligerKing** [comment]
----Forgified Fabric API
additional structures
advancement plaques
alexs mobs
apple skin
aquamirae
Architectury API
Artifacts
Athena
Bagus Lib
Balm (Forge Edition)
Better Combat [Fabric & Forge]
Better McDonald's Mod
Better Smithing Table
Better Villages - Forge
Biomes O' Plenty
Bookshelf
Carry On
Chipped
Chisels & Bits - For Forge
Christmas Festivity
Citadel
Cloth Config API
Clumps
Comforts (Fabric/Forge/Quilt)
----Connector Extras
Continents
Controlling
Corail Tombstone
Cosmetic Armor Reworked
Create
Create : Misc & Things
Create : Teleporters!
Create Big Cannons
Create Central Kitchen
Create Compact Exp
Create Compressed
Create Confectionery
Create Crafts & Additions
Create Deco
Create Decoration Casing
Create Encased
Create Enchantment Industry
Create Recycle Everything
Create Sabers
Create Stuff & Additions
Create: Balanced Flight (Angel Ring)
Create: Bells & Whistles
Create: Broken Bad
Create: christmass
Create: Extended Cogwheels
Create: Interiors
Create: Steam 'n' Rails
Creeper Overhaul
Cristel Lib
Curios API (Forge/NeoForge)
Deeper and Darker
Dungeon Crawl
Enchantment Descriptions
End Remastered
Even Better Amethyst [Forge]
Explorify – Dungeons & Structures
Fantasy's Dice
Fantasy's Furniture
Fast Leaf Decay
Framework
GeckoLib
Goblin Traders
Hunter'sReturn
Iceberg [Forge]
Iron Chests
Jolly Boxes
Just Enough Items (JEI)
Just Enough Professions (JEP)
Just Enough Resources (JER)
Kiwi 🥝 (Forge)
Legendary Tooltips [Forge]
Library Ferret - Forge
Lootr (Forge)
Macaw's Lights and Lamps
Macaw's Trapdoors
Mahou Tsukai
Maiden's Merrymaking - A Minecraft C
MC Dungeons Weapons
Medieval Music[Forge/Fabric]
MmmMmmMmmMmm (Target Dum
Moonlight Lib
Mouse Tweaks
MrCrayfish's Furniture Mod
Obscure API (Forge)
Paragliders
playerAnimator
Polymorph (Fabric/Forge/Quilt)
Prism [Forge]
Repurposed Structures (Neoforge/For
Resourceful Config
Resourceful Lib
Searchables
Simple Weapons for Better Combat
----Sinytra Connector
Snow Pig [Forge]
Snow Under Trees
Snow! Real Magic! ⛄ (Forge)
Snowy Spirit
Sophisticated Backpacks
Sophisticated Core
Supplementaries
Tarot Cards
TerraBlender (Forge)
The Aether
The One Probe
The Twilight Forest
Towers of the Wild Modded
Towers of the Wild: Additions
Towns and Towers
Traveler's Titles (Forge)
Voidscape
Waystones
Xaero's Minimap
Xaero's World Map
YUNG's API (Forge)
YUNG's Better Desert Temples (Forg
YUNG's Better Dungeons (Forge)
YUNG's Better End Island (Forge)
YUNG's Better Mineshafts (Forge)
YUNG's Better Nether Fortresses (Fo
YUNG's Better Ocean Monuments (Fo
YUNG's Better Strongholds (Forge)
YUNG's Better Witch Huts (Forge)
YUNG's Bridges (Forge)
YUNG's Extras (Forge)

i have all 3 mods that were stated in the announcements channel that are needed

forge version is 47.2.0

**Comment by VilligerKing** [comment]
also another note, the error message when the mc launcher pops up specifically mentions mcdw, so i dont think its any other mods

**Comment by VilligerKing** [comment]
@chronosacaria ive found out it is the Clumps mod that makes it not want to load, i have modpack where it is just clumps, MCDW, cloth config api, connector extras, forgified and sinytra connector and it wont load the game, giving me the same error message

**Comment by chronosacaria** [comment]
@VilligerKing Just checking, are you using the Forge or Fabric version of Clumps?

**Comment by PvtFudgepants** [comment]
I was having the same issue. Switching to the fabric version of Clumps fixed it and allowed me to load the game.

**Comment by chronosacaria** [comment]
Since the most common issue that people are having has been resolved, I'm going to close this issue with a notice on how to fix that issue:

# If you are crashing whilst using MCDW on Forge, check the following: 
- make sure that you are using the Fabric Version of Clumps, if you are using Clumps. 
  - This is because we hook into an even that is only present on the Fabric Version to allow for some of our enchantments to work with Clumps properly.
