### ISSUE TITLE
[Bug Report]: This mod does not support Opitfine！

### ISSUE THREAD

**Issue by Puzzle86cn** [chronosacaria/MCDungeonsWeapons#255]
### Describe the bug; What happened?

This mod does not support Opitfine！

### Expected Behavior

Forgified Fabric API's problem.

### Mod Version

1.20.1

### Minecraft Launcher

Vanilla

### Operating System

Windows

**Comment by chronosacaria** [comment]
@Puzzle86cn MCDX will never support Optifine, this is 100% intentional. Please use Rubidium and Oculus instead.
