### ISSUE TITLE
[Bug Report]: Crashing on load [Forge]

### ISSUE THREAD

**Issue by mehr0** [chronosacaria/MCDungeonsWeapons#258]
### Describe the bug; What happened?

When booting up minecraft it crashes with an error -1
[latest.log](https://github.com/chronosacaria/MCDungeonsWeapons/files/14364621/latest.log)

### Expected Behavior

Minecraft loaded normally without crashes

### Mod Version

1.20.1

### Minecraft Launcher

CurseForge

### Operating System

Windows

**Comment by chronosacaria** [comment]
@mehr0 You are missing the [Connector Extras](https://www.curseforge.com/minecraft/mc-mods/connector-extras) mod. Please, be sure to read all of the documentation provided by [The Sinytra Connector](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector). That will give you the best chances at success. Please remember, the Connector is still in active development and bugs should be expected. If you continue to run into issues, please consider hopping into the [Discord](https://www.discord.gg/HGQUUSrwt3) where we can help you more in real-time
