### ISSUE TITLE
[Bug Report]: CurseForge and Modrinth upload 9.0.1 seem to be missing dependencies

### ISSUE THREAD

**Issue by fzzyhmstrs** [chronosacaria/MCDungeonsWeapons#259]
### Describe the bug; What happened?

Go to CF or Modrinth and look at the 9.0.1 file pages, and I don't see any dependencies listed.

### Expected Behavior

Seeing dependencies.

### Mod Version

9.0.1

### Minecraft Launcher

Vanilla

### Operating System

Windows

### Additional context

Version 9.0.0 CF:
![image](https://github.com/chronosacaria/MCDungeonsWeapons/assets/72876796/94cd71ae-548e-4d51-8430-06a76a56e61d)

Version 9.0.1 CF:
![image](https://github.com/chronosacaria/MCDungeonsWeapons/assets/72876796/787b9c57-6f38-498d-bf32-fcd70a9dbf12)

Version 9.0.0 Modrinth:
![image](https://github.com/chronosacaria/MCDungeonsWeapons/assets/72876796/2cb8a61c-1bfe-48b5-9ece-6aa6dd0f94b1)

Version 9.0.1 Modrinth:
![image](https://github.com/chronosacaria/MCDungeonsWeapons/assets/72876796/d9f23319-07b2-40fb-8bdd-94c8341771aa)

**Comment by chronosacaria** [comment]
Thanks for catching this. It was the same case with MCDAR, which has been corrected :)
