### ISSUE TITLE
[Bug Report]: Enchantments are still being registered, with isEnabled set to false

### ISSUE THREAD

**Issue by purejosh** [chronosacaria/MCDungeonsWeapons#263]
### Describe the bug; What happened?

In my configuration, I have disabled `DYNAMO`, `GROWING`, and `REFRESHMENT`. However, they are still registered on the server as enchanted books, and they still appear on their assigned weapons.

### Expected Behavior

Config to prevent enchantments from being registered. 

### Mod Version

9.0.1

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

n/a

### Additional context

Here's my config file. 😄
https://gist.github.com/purejosh/b2b776696cb4ea7a92559d11adbd9da7

**Comment by chronosacaria** [comment]
Fixed by https://github.com/chronosacaria/MCDungeonsWeapons/commit/3148878fa560ab238e6ee476a83f73f922259be7 and https://github.com/chronosacaria/MCDungeonsWeapons/commit/9a1bd1df50e8c8f149efcec0df495c6b621cc6be
