### ISSUE TITLE
[Bug Report]:  The Weapons and Armors. The Forge version cannot enter the game,it's still Fabric

### ISSUE THREAD

**Issue by Puzzle86cn** [chronosacaria/MCDungeonsWeapons#264]
### Describe the bug; What happened?

 The Weapons and Armors. The Forge version cannot enter the game,it's still Fabric

### Expected Behavior

Thank you

### Mod Version

1.20.1

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Additional context

![bug](https://github.com/chronosacaria/MCDungeonsWeapons/assets/154900983/ebdc4a45-e8df-4c26-b6fa-e3179002e4a8)
![bug](https://github.com/chronosacaria/MCDungeonsWeapons/assets/154900983/765dc5f4-9714-4af0-b670-fa0dfd3b55db)

**Comment by fzzyhmstrs** [comment]
Please make sure you have all of the supporting mods installed per the below:

When using MCDX on Forge, it is important to make sure that you have the following mods:
So, anything marked with a 🟢 is required. Anything marked with a 🟡 is optional

CurseForge
🟢 Sinytra Connector:
https://www.curseforge.com/minecraft/mc-mods/sinytra-connector/
🟢 Connector Extras:
https://www.curseforge.com/minecraft/mc-mods/connector-extras/
🟢 Forgified Fabric API (in place of the Fabric API):
https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api/
🟢 Cloth Config API (Forge or Fabric Version):
https://www.curseforge.com/minecraft/mc-mods/cloth-config/
🟡 Clumps (Fabric Version), if you're using Clumps:
https://www.curseforge.com/minecraft/mc-mods/clumps/

Modrinth
🟢 Sinytra Connector:
https://modrinth.com/mod/connector
🟢 Connector Extras:
https://modrinth.com/mod/connector-extras
🟢 Forgified Fabric API (in place of the Fabric API):
https://modrinth.com/mod/forgified-fabric-api
🟢 Cloth Config API (Forge or Fabric Version):
https://modrinth.com/mod/cloth-config
🟡 Clumps (Fabric Version), if you're using Clumps:
https://modrinth.com/mod/clumps

**Comment by chronosacaria** [comment]
@Puzzle86cn As fzzyhmstrs said, make sure you have all the right mods to make sure it works. As the solution has been provided, this issue shall be closed.
