### ISSUE TITLE
[Bug Report]: both mc dungeons weapons and armors don't seem to recognize cloth config

### ISSUE THREAD

**Issue by gabvichiato** [chronosacaria/MCDungeonsWeapons#265]
### Describe the bug; What happened?

all the dependencies are installed, everything is updated and i double checked it. upon launching, the game starts just fine, but it doesn't get to the initial screen and just says there's no cloth-config2 installed, which left me asking myself what could that be, as there's no cloth-config2 anywhere. other people seemed to have had issues with this happening, but no idea how to solve it

### Expected Behavior

instead of booting correctly and taking me to the main screen, it just says i don't have a dependency (which i do have) and that's it

### Mod Version

1.20.1

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

my own, nothing too crazy in there

**Comment by chronosacaria** [comment]
@gabvichiato Use the Fabric version of Cloth Config. Also, make sure that if you are using Clumps that you use the Fabric version of Clumps. This is an issue with Cloth Config not using the same namespace for their Forge and Fabric versions

**Comment by gabvichiato** [comment]
i've already tried it too and it didn't work anyway, but i'm trying to change something in sinytra's connector configs. as seen here, maybe adding another alias makes it detectable? as seen here https://sinytra.org/docs/connector/configuration
as i have no idea how to effectively change and make it work, i'm accomplishing nothing, but maybe you could tell me if it makes any sense. ty!

**Comment by chronosacaria** [comment]
@gabvichiato Can you post the crash log? I can take a look at it
