### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by Memory-Yzf** [chronosacaria/MCDungeonsWeapons#266]
### Describe the bug; What happened?

Why is the same file displayed on the server out of sync.
Make sure there is no difference between the two files.

### Expected Behavior

Unable to access server.

### Mod Version

9.0.1

### Minecraft Launcher

Other

### Operating System

Windows

### Additional context

![1](https://github.com/chronosacaria/MCDungeonsWeapons/assets/102323087/bca8ac0d-d46f-4505-b8d4-454aa33c73e2)
![2](https://github.com/chronosacaria/MCDungeonsWeapons/assets/102323087/079854b4-abab-45af-8619-35c42efc12db)

**Comment by chronosacaria** [comment]
@1625926165 你从哪里下载的修改器？文件名没有意义

**Comment by chronosacaria** [comment]
此外，该文件似乎被修改过。它应该是 1,448 KB。但是，您在图片中显示的文件是 1,365 KB

**Comment by Memory-Yzf** [comment]
> @1625926165 你从哪里下载的修改器？文件名没有意义

Thank you for your reply. I have found the problem. It seems that the MCDW configuration of the client is different from that of the server, which also leads to the failure to access the server
