### ISSUE TITLE
Prospector enchantment bugged

### ISSUE THREAD

**Issue by BrekiTomasson** [chronosacaria/MCDungeonsWeapons#27]
The code for the Prospector enchantment has a faulty statement in it, you're checking `if (McdwEnchantsConfig.getValue("mixin_exploding"))`

**Comment by chronosacaria** [comment]
And that is what I get for rushing. Thanks for catching that. I can fix that easily

**Comment by BrekiTomasson** [comment]
It's an easy mistake to make, I've had similar issues plenty of times before when copy/pasting code. :)
