### ISSUE TITLE
[Bug Report]: mod, half broke when updated?

### ISSUE THREAD

**Issue by MrGalzraVoid** [chronosacaria/MCDungeonsWeapons#270]
### Describe the bug; What happened?

was updating the mods in my mini pack along with this mod, did so then loaded it up. MC Dungeons Weapons is half working. the weapons are gone but the enchantment books are still there.

### Expected Behavior

I expected to still have the shield I was carrying, that was the tip off something was wrong. 

![Desktop Screenshot 2024 04 15 - 01 16 23 84](https://github.com/chronosacaria/MCDungeonsWeapons/assets/47510048/1f611436-752d-4d5e-b7d3-34b8afe18933)
![Desktop Screenshot 2024 04 15 - 01 16 30 71](https://github.com/chronosacaria/MCDungeonsWeapons/assets/47510048/bd628a6b-c65e-4174-bcfe-c6f1d8566178)

### Mod Version

9.0.2

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

My Own Mini Pack

### Additional context

was all working fine with no issues before I updated things.

**Comment by chronosacaria** [comment]
As noted in the update notes: you must delete your MCDW configs. Let them regen and everything will work properly

**Comment by MrGalzraVoid** [comment]
Gotcha, I will need to remember that.
