### ISSUE TITLE
[Bug Report]: Incompatibility with Apotheosis?

### ISSUE THREAD

**Issue by abby-cadabra** [chronosacaria/MCDungeonsWeapons#274]
### Describe the bug; What happened?

I'm running this mod on Forge 1.20.1 alongside Apotheosis.

Having a weird error where, about half the time when I go to enchant a Book, it will return "Limited Enchantability" or else be completely blank.

![2024-04-17_11 41 44](https://github.com/chronosacaria/MCDungeonsWeapons/assets/132413818/a36dcd53-7138-4133-9a6e-5c856987134b)

![2024-04-17_11 41 59](https://github.com/chronosacaria/MCDungeonsWeapons/assets/132413818/87ab0d01-755f-4d81-9b0a-9c5bcee562d2)

When I look at the latest.log, I see something happening around the time of the bug that seems to relate to MCDW:

[11:42:09] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundContainerButtonClickPacket@1a75d869, suppressing error
java.lang.NullPointerException: Cannot invoke "chronosacaria.mcdw.bases.McdwDagger.m_7968_()" because the return value of "chronosacaria.mcdw.enums.DaggersID.getItem()" is null

Wondering if this might point to an incompatibility with Apotheosis?

### Expected Behavior

Would expect a range of enchantments to be available for the Book

### Mod Version

9.0.2

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

Self-made

**Comment by chronosacaria** [comment]
@abby-cadabra Did you update from an older version of MCDW?

**Comment by abby-cadabra** [comment]
Quite probably - been using this mod for a while. 

I see there is something about deleting configs on the latest version. I always auto-update through Curseforge. I'll try doing that and see how it goes.

**Comment by abby-cadabra** [comment]
Yep, that seems to fix it. Thanks for the quick reply. Hopefully this will be helpful if anyone else encounters the same problem.

**Comment by chronosacaria** [comment]
@abby-cadabra Yeah, when I saw the enum, that is what made me think that. The changelog does say to delete the configs, but CurseForge isn't great at showing that to the user. I'm glad it was a quick fix though :)
