### ISSUE TITLE
[Bug Report]: Poison Cloud, Radiance and Weakening Enchantments don't work

### ISSUE THREAD

**Issue by kineticV** [chronosacaria/MCDungeonsWeapons#277]
### Describe the bug; What happened?

All enchantments that should spawn a lingering potion effect never spawn the lingering potion effect. This includes Poison Cloud, Radiance and Weakening enchantments, and includes innate enchants and when I apply enchants with a anvil. This worked on a previous version of the mod.

### Expected Behavior

Weapons with these enchantments should spawn the lingering potion effects sometimes.

### Mod Version

mcdw-5.0.13-1.19

### Minecraft Launcher

MultiMC

### Operating System

Windows

### Additional context

Minecraft version 1.19.2

**Comment by chronosacaria** [comment]
@kineticV Delete the MCDW configs and reload. If this does not resolve your issue, update to the latest version. 1.19.x is no longer supported.

**Comment by chronosacaria** [comment]
As this issue is not present in the latest version and there has been no follow-up on the OP's issue, this issue shall be closed for inactivity
