### ISSUE TITLE
Impossible to tell the difference between forge and fabric verison, also confusion with dependancies

### ISSUE THREAD

**Issue by Steak-Fish** [chronosacaria/MCDungeonsWeapons#279]
### Is your feature request related to a problem? Please describe.

My friend was installing this into a modpack, and we spent like 10 minutes trying to find out why it isn't working. I double checked the curseforge repo to verify version numbers, and they matched the 1.20.1 forge version, but there wasn't a forge or fabric label so I just assumed it was cross compatible. 

He sent me the mod and I opened it up and discovered it was for fabric.

### Describe the solution you'd like

Please rename the jars to something like
mcdw_modversion-forge/fabric_mcversion.jar

### Describe alternatives you've considered

I have considered ~killing myself~ removing the mod from out pack, but my friend INSISTED not to. I nearled'd to thisn't.

### Additional context

I just BUSTED!!!

Sorry for being goofy.

**Comment by chronosacaria** [comment]
@CoolManTheCool 
The reason that it is impossible to tell the difference is that they are the same file, so you are correct in that they are cross compatible. You just need to use the appropriate dependencies:

-----------

When using MCDX on Forge, it is important to make sure that you have the following mods:
So, anything marked with a  is required. Anything marked with a  is optional

# CurseForge
🟢 Sinytra Connector:
https://www.curseforge.com/minecraft/mc-mods/sinytra-connector/
🟢 Connector Extras:
https://www.curseforge.com/minecraft/mc-mods/connector-extras/
🟢 Forgified Fabric API (in place of the Fabric API):
https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api/
🟢 Cloth Config API (Forge Version*):
https://www.curseforge.com/minecraft/mc-mods/cloth-config/
- If you are using a version of the Sinytra Connector before 40, 
     use the Fabric version

🟡 Clumps (Fabric Version), if you're using Clumps:
https://www.curseforge.com/minecraft/mc-mods/clumps/

-----------

# Modrinth
🟢 Sinytra Connector:
https://modrinth.com/mod/connector
🟢 Connector Extras:
https://modrinth.com/mod/connector-extras
🟢 Forgified Fabric API (in place of the Fabric API):
https://modrinth.com/mod/forgified-fabric-api
🟢 Cloth Config API (Forge Version*):
https://modrinth.com/mod/cloth-config
- If you are using a version of the Sinytra Connector before 40, 
     use the Fabric version

🟡 Clumps (Fabric Version), if you're using Clumps:
https://modrinth.com/mod/clumps

If you need any more help with anything else, don't hesitate to ask in the Discord. You can get there via this link: https://www.discord.gg/timefall!

--------

Also, in the future, do not joke about suicidality. Further situations like that shall result in your issue report being closed without an answer.

**Comment by chronosacaria** [comment]
Also, the naming convention that you suggest doesn't follow SemVer and will not be taken into consideration for that reason. Thank you for understanding

**Comment by chronosacaria** [comment]
As this is a requested enhancement and the requested enhancement doesn't follow SemVer, this issue shall be closed.
