### ISSUE TITLE
error [Bug Report]: 

### ISSUE THREAD

**Issue by zc1108aaa** [chronosacaria/MCDungeonsWeapons#286]
### Describe the bug; What happened?

0

### Expected Behavior

0

### Mod Version

0,9,4

### Minecraft Launcher

Vanilla

### Operating System

Windows

### Additional context

[crash-2024-06-24_16.56.48-client.txt](https://github.com/user-attachments/files/15952484/crash-2024-06-24_16.56.48-client.txt)

**Comment by chronosacaria** [comment]
Due to an lack of context for the crash and minimal information to work from, this issue shall be closed
