### ISSUE TITLE
[Question] Does the bag of soul enchantment stack when having it on different equipped armor pieces?

### ISSUE THREAD

**Issue by msr8** [chronosacaria/MCDungeonsWeapons#287]
Basically what I am trying to ask is it better to have the "Bag of Souls III" enchantment on all my armor pieces (ie helmet, chestplate, leggings, and boots) than just having it on one of my armor pieces?

**Comment by chronosacaria** [comment]
@msr8 Yep! It definitely stacks!

**Comment by msr8** [comment]
Thank you!
