### ISSUE TITLE
Bows and crossbows...

### ISSUE THREAD

**Issue by JayCeeCreates** [chronosacaria/MCDungeonsWeapons#29]
They turn into their large sprites whenever I prepare them. I hope it's not intentional or just a placeholder because it ruins the immersion...

**Comment by chronosacaria** [comment]
I'm going to need you to be more specific because this is not enough information to go off of

**Comment by JayCeeCreates** [comment]
I hope this GIF helps. Notice the hotbar.
![qVD9TZDWbk](https://user-images.githubusercontent.com/28774264/108230907-31c7e780-717c-11eb-92ab-3e3b6af43064.gif)

So I just looked into the issue again and it seems like it was due to **incompatibility between this mod and XisumaVoid's Item Stitching Fix from VanillaTweaks**. You may close this issue if no further fix is needed-

**Comment by chronosacaria** [comment]
I didn't know that the Stitching Fix would cause that; but that is good to know :)
