### ISSUE TITLE
FPS Lag

### ISSUE THREAD

**Issue by lukasgamer877** [chronosacaria/MCDungeonsWeapons#290]
### Describe the bug; What happened?

When I have a weapon like this in my inventory, it drops at least 80 fps and I don't know why. I have already disabled all the animations and nothing.

### Expected Behavior

The mod should not lower my fps so much

### Mod Version

1.55.0

### Minecraft Launcher

Vanilla

### Operating System

Windows

**Comment by chronosacaria** [comment]
@lukasgamer877 No MCDW weapon had animations nor is that the correct version of MCDW as we don't have a version with that number. You may be confusing MCDW with another mod. As this is not from MCDW, I'm gonna close the issue, but you can still respond in this issue post. If we can determine which mod you meant to make the issue for, I can try to get you a link for that mod to mark an issue there :)

**Comment by lukasgamer877** [comment]
That's right, it confuses me with another mod. I'm sorry
