### ISSUE TITLE
[Bug Report]: Busy Bee not working; Soul Devourer cannot be disabled

### ISSUE THREAD

**Issue by ihymyly** [chronosacaria/MCDungeonsWeapons#292]
### Describe the bug; What happened?

Upon editing the config and disabling Soul Devourer, the game can not start up, and a large crash file (containing contents about the Soul Scythe). Busy Bee also doesn't summon any bees or make nearby bees assist the user.

### Expected Behavior

Soul Devourer would be removed from the game, but Soul Scythe still works fine without it. Bees would be summoned, or nearby bees would assist the player.

### Mod Version

9.0.4

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

None

**Comment by chronosacaria** [comment]
@ihymyly These are technically two different issues. The disabling of the enchantments is something that we knew about (unfortunately), but we're going to be fixing that.

For the bees to be summoned, you must be holding a bee's stinger (dropped from a bee) in your offhand whilst attacking a mob with a weapon with the Busy Bee enchantment

**Comment by chronosacaria** [comment]
Issue 292 - Partially addressed
Bug: Config Crash
Works as intended: Busy Bee enchantment

**Comment by ihymyly** [comment]
Understood. Busy Bees still seems to not work. I'm only using (Fabric) Better Combat and Universal Enchants, with Dummy to test.

Skip 8 seconds, I forgot to cut.

https://github.com/user-attachments/assets/7fb1aa52-7357-4c90-acc6-e01d0fe9eef7

**Comment by chronosacaria** [comment]
> Understood. Busy Bees still seems to not work. I'm only using (Fabric) Better Combat and Universal Enchants, with Dummy to test.
> 
> Skip 8 seconds, I forgot to cut.
> Minecraft_.1.20.1.-.Singleplayer.2024-07-28.05-13-30.1.mp4

So, the thing you need in the offhand isn't the sword. It is the stinger that drops from a bee when you kill it. Unfortunately, the original naming doesn't help with the confusion. At the risk of sounding vulgar: the thing you need to hold in your offhand is the pin-like thing that is on a bee's butt

**Comment by ihymyly** [comment]
Oh the actual "stinger", not the weapon. I finally understand now lol, thank you so much. I apologize for the lack of initial understanding.

**Comment by chronosacaria** [comment]
@ihymyly No worries, at all. I blame English and Mojang for their naming conventions XD
