### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by Astruwu** [chronosacaria/MCDungeonsWeapons#294]
### Describe the bug; What happened?

Loading a forge modpack with [Sinytra Connector](https://github.com/Sinytra/Connector) as the forge-fabric bridge.
adding this mod when a fabric bridge is active makes it assume its a fabric mod i think, since it works just fine when i disable sinytra or when i disable this mod and have sinytra and its dependencies active.

### Expected Behavior

it should be using the forge code instead of the fabric part of the code since the forge part should in theory be more stable on a native forge loader

### Mod Version

9.0.4

### Minecraft Launcher

Other

### Operating System

Windows

### Modpack

Unreleased modpack i am putting together

### Additional context

[crash-2024-08-18_23.21.52-client.txt](https://github.com/user-attachments/files/16652377/crash-2024-08-18_23.21.52-client.txt)
if this is not an issue and i am just really stupid please let me know aswell since i'd love to learn!

**Comment by fzzyhmstrs** [comment]
Forge Clumps does not work with MCDW. Please install the Fabric Version of Clumps (you may have to manually add it like other fabric mods, depending on your launcher).

**Comment by chronosacaria** [comment]
@Astruwu As stated by @fzzyhmstrs, you need the Fabric version of Clumps. And you're not stupid. You're learning :)

**Comment by Astruwu** [comment]
This worked! thank you very much, also mb for not reading all the way down to the bottom of the q&a page.
