### ISSUE TITLE
CRASH!!!: Incompatibility with Clumps mod

### ISSUE THREAD

**Issue by TheSexyYeti** [chronosacaria/MCDungeonsWeapons#296]
### Describe the bug; What happened?

When the Clumps mod is installed. It caused the game to crash during initial loading. Here's the crash log.  https://pastebin.com/ArLxfTih

### Expected Behavior

Crash

### Mod Version

9.0.4

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

custom modpack

**Comment by chronosacaria** [comment]
@TheSexyYeti Remove the Forge version of Clumps and replace it with the Fabric version of Clumps as stated on the MCDW Mod Page FAQ
