### ISSUE TITLE
[Bug Report]: all items labeled minecraft:air, games crashes when pulling up any of their respective create tabs and this only happens in a multiplayer server

### ISSUE THREAD

**Issue by Kajiyaa** [chronosacaria/MCDungeonsWeapons#298]
### Describe the bug; What happened?

[latest.log](https://github.com/user-attachments/files/16936670/latest.log)

list of mods:

alexscaves-1.1.5.jar
alexsmobs-1.22.8.jar
appleskin-forge-mc1.20.1-2.5.1.jar
appliedenergistics2-forge-15.2.13.jar
architectury-9.2.14-forge.jar
athena-forge-1.20.1-3.1.2.jar
azurelib-neo-1.20.1-2.0.34.jar
bellsandwhistles-0.4.3-1.20.x.jar
bettercombat-forge-1.8.6+1.20.1.jar
Bookshelf-Forge-1.20.1-20.2.13.jar
born_in_chaos_[Forge]1.20.1_1.3.1.jar
butcher-2.5.4-forge-1.20.1.jar
bygonenether-1.3.2-1.20.x.jar
carryon-forge-1.20.1-2.1.2.7.jar
Chipped-forge-1.20.1-3.0.6.jar
citadel-2.6.0-1.20.1.jar
cloth-config-11.1.118-forge.jar
Connector-1.0.0-beta.45+1.20.1.jar
ConnectorExtras-1.11.2+1.20.1.jar
constructionwand-1.20.1-2.11.jar
copycats-2.1.2+mc.1.20.1-forge.jar
cosmeticarmorreworked-1.20.1-v1a.jar
create-1.20.1-0.5.1.f.jar
create-stuff-additions1.20.1_v2.0.4a.jar
createaddition-1.20.1-1.2.4e.jar
createbigcannons-5.5.1-mc.1.20.1-forge.jar
createdeco-2.0.2-1.20.1-forge.jar
create_enchantment_industry-1.20.1-for-create-0.5.1.f-1.2.9.d.jar
create_jetpack-forge-4.2.1.jar
create_misc_and_things_ 1.20.1_4.0A.jar
CreativeCore_FORGE_v2.11.37_mc1.20.1.jar
CullLessLeaves-Reforged-1.20.1-1.0.5.jar
curios-forge-5.10.0+1.20.1.jar
DungeonsArise-1.20.x-2.1.58-release.jar
embeddium-0.3.31+mc1.20.1.jar
EnchantmentDescriptions-Forge-1.20.1-17.1.18.jar
enchantmenttransfer-0.0.6-1.20.1.jar
Explorify v1.6.1 f10-48.jar
fabric-api-0.92.2+1.11.8+1.20.1.jar
FarmersDelight-1.20.1-1.2.4.jar
FastSuite-1.20.1-5.0.1.jar
ferritecore-6.0.1-forge.jar
Fibers Gun Pack-1.1.3.jar
formations-1.0.2a-forge-mc1.20.2.jar
formationsnether-1.0.5.jar
framework-forge-1.20.1-0.7.7.jar
geckolib-forge-1.20.1-4.4.9.jar
iceandfire-2.1.13-1.20.1-beta-5.jar
immersive_aircraft-1.0.1+1.20.1-forge.jar
interiors-0.5.4+forge-mc1.20.1.jar
inventorysorter-1.20.1-23.0.1.jar
Jade-1.20.1-forge-11.9.2.jar
jei-1.20.1-forge-15.12.2.51.jar
journeymap-1.20.1-5.10.2-forge.jar
JustEnoughResources-1.20.1-1.4.0.247.jar
kotlinforforge-4.11.0-all.jar
letsdo-API-forge-1.2.15-forge.jar
letsdo-vinery-forge-1.4.28.jar
lionfishapi-1.9.jar
list.txt
lmft-1.0.4+1.20.1-forge.jar
lootr-forge-1.20-0.7.34.89.jar
lradd-1.20.1-0.2.2.jar
lrarmor-1.20.1-0.1.4.3.jar
L_Enders_Cataclysm-1.99.6-1.20.1.jar
man_of_many_planes-0.1.0+1.20.1-forge.jar
mcda-5.0.2.jar
mcdw-9.0.4.jar
modernfix-forge-5.19.4+mc1.20.1.jar
mowziesmobs-1.6.5.jar
nethersdelight-1.20.1-4.0.jar
notenoughanimations-forge-1.7.6-mc1.20.1.jar
OctoLib-FORGE-0.4.2+1.20.1.jar
Patchouli-1.20.1-84-FORGE.jar
Placebo-1.20.1-8.6.2.jar
player-animation-lib-forge-1.0.2-rc1+1.20.jar
polymorph-forge-0.49.5+1.20.1.jar
refurbished_furniture-forge-1.20.1-1.0.6.jar
relics-1.20.1-0.8.0.6.jar
resourcefullib-forge-1.20.1-2.1.29.jar
samurai_dynasty-0.0.48-1.20.1-neo.jar
ScorchedGuns-0.2.3-1.20.1_fix.jar
simplehats-forge-1.20.1-0.3.2.jar
simplyswords-forge-1.56.0-1.20.1.jar
spartanfire-1.20.1-2.1.0.jar
spartantoolkit-1.20.1-1.4.2.jar
spartantwilight-1.20.1-3.1.0.jar
SpartanWeaponry-1.20.1-forge-3.1.3-all.jar
Steam_Rails-1.6.4+forge-mc1.20.1.jar
StorageDrawers-1.20.1-12.6.4.jar
tacz-1.20.1-1.0.2-release.jar
The_Graveyard_3.1_(FORGE)_for_1.20.1.jar
tombstone-1.20.1-8.7.1.jar
travelersbackpack-forge-1.20.1-9.1.15.jar
twilightforest-1.20.1-4.3.2508-universal.jar
valhelsia_core-forge-1.20.1-1.1.2.jar
valhelsia_furniture-forge-1.20.1-1.1.3.jar
valhelsia_structures-forge-1.20.1-1.1.2.jar
[1.20.1-forge]-Epic-Knights-9.8.jar

this encompasses both weapon and armor mods

when on a solo-world the mod loads up just fine, every time is labeled as is and nothing seemed to be out of wack, how ever when i load into a multi-player server with a friend, the creative tabs for the mod all end up labeled as "minecraft:air" and proceed to crash the game when ever loaded, and recently we found a chest with one of the dungeon weapons, and upon opening it it seems to crash the game because of this issue, afaik personally.

### Expected Behavior

All mod tabs should be loading properly, names of every individual item working labeled properly with stats and usage, how ever every item is an unusable item labeled "minecraft:air" while still maintaining the visual sprites and enchantment sheens, game crash when tabs or items are loaded in any way.

### Mod Version

9.0.4

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

Custom Modpack

### Additional context

![image](https://github.com/user-attachments/assets/14cce3a6-8dd9-44a9-89d5-966bdc2ab708)

**Comment by chronosacaria** [comment]
# Items are Air Issue
@Kajiyaa Well, that's definitely a first. So, there does seem to be a discrepancy between the mod list you posted and the mod list from the log. Are you sure that is the correct log? According to the log, your mods are as follows:
```
[14:48:52] [main/INFO]: Loading 127 mods:
	- ae2 15.2.13
	- alexscaves 1.1.5
	- alexsmobs 1.22.8
	- appleskin 2.5.1+mc1.20.1
	- architectury 9.2.14
	- athena 3.1.2
	- azurelib 2.0.31
	- bellsandwhistles 0.4.3-1.20.x
	- bettercombat 1.8.6+1.20.1
	- betterdungeons 1.20-Forge-4.0.4
	- betterfortresses 1.20-Forge-2.0.6
	- betterfpsdist 1.20.1-4.4
	- bettermineshafts 1.20-Forge-4.0.4
	- betteroceanmonuments 1.20-Forge-3.0.4
	- betterstrongholds 1.20-Forge-4.0.3
	- bookshelf 20.2.13
	- born_in_chaos_v1 1.0.0
	- botarium 2.3.4
	- butcher 2.5.4
	- butchersdelight 1.20.12.1.0
	- bygonenether 1.3.2
	- carryon 2.1.2.7
	- cataclysm 1.99.5
	- chickenchunks 2.10.0.100
	- chipped 3.0.6
	- citadel 2.6.0
	- cloth_config 11.1.118
	- clumps 12.0.0.4
	- codechickenlib 4.4.0.512
	- controlling 12.0.2
	- cosmeticarmorreworked 1.20.1-v1a
	- create 0.5.1.f
		\-- flywheel 0.6.10-7
	- create_compressed 1.0.1
	- create_crush_everything 1.0.2
	- create_easy_structures 0.1.1
	- create_enchantment_industry 1.2.9.d
		\-- create_dragon_lib 1.4.3
	- create_things_and_misc 1.0.0
	- createaddition 1.20.1-1.2.4e
	- createbigcannons 5.5.1+mc.1.20.1-forge
		\-- ritchiesprojectilelib 2.0.0-dev+mc.1.20.1-forge-build.182
	- createdeco 2.0.2-1.20.1-forge
	- createloveandwar 0.2-1.20.1
	- createtaczauto 1.0.1
	- creativecore 2.11.37
	- cristellib 1.1.5
	- crystal_clear 2.1-Beta
	- culllessleaves 1.20.1-1.0.5
	- cupboard 1.20.1-2.7
	- curios 5.10.0+1.20.1
	- destroy 0.8
	- disenchanting 2.2.3
	- doapi 1.2.15
		\-- terraform 7.0.1
	- dummmmmmy 1.20-1.8.19
	- embeddium 0.3.31+mc1.20.1
		\-- rubidium 0.7.1
	- enchdesc 17.1.18
	- explorerscompass 1.20.1-1.3.3-forge
	- explorify 1.6.1
	- fallingleaves 2.1.0
	- farmersdelight 1.20.1-1.2.4
	- farmersrespite 1.20.1-2.1
	- fastleafdecay 32
	- fastsuite 5.0.1
	- ferritecore 6.0.1
	- fibers 1.1.3
	- flansmod 0.4
	- forge 47.3.7
	- framework 0.7.7
	- geckolib 4.4.9
	- immersive_aircraft 1.0.1+1.20.1
	- immersive_armors 1.6.1+1.20.1
	- interiors 0.5.4+forge-mc1.20.1
	- jade 11.9.2+forge
	- jei 15.17.0.74
	- jeresources 1.4.0.247
	- journeymap 5.10.2
	- letmedespawn 1.2.1
	- lionfishapi 1.9
	- lmft 1.0.4+1.20.1
	- lootr 0.7.34.87
	- lradd 0.2.2
	- magistuarmory 9.8
	- man_of_many_planes 0.1.0+1.20.1
	- mcwdoors 1.1.1
	- mcwfences 1.1.2
	- minecraft 1.20.1
	- modernfix 5.19.4+mc1.20.1
	- moonlight 1.20-2.12.17
		\-- mixinextras 0.3.6
	- mousetweaks 2.25.1
	- nethersdelight 1.20.1-4.0
	- oculus 1.7.0
	- philipsruins 4.4.1
	- placebo 8.6.2
	- playeranimator 1.0.2-rc1+1.20
	- pointblank 1.6.7
	- polymorph 0.49.5+1.20.1
		\-- spectrelib 0.13.15+1.20.1
	- puzzleslib 8.1.22
		\-- puzzlesaccessapi 8.0.7
	- railways 1.6.4+forge-mc1.20.1
	- refurbished_furniture 1.0.6
	- resourcefullib 2.1.29
	- rustic_engineer 1.0.0
	- samurai_dynasty 0.0.48-1.20.1-neo
	- scguns 0.1.5
	- searchables 1.0.3
	- skinlayers3d 1.6.7
	- sophisticatedbackpacks 3.20.6.1064
	- sophisticatedcore 0.6.25.632
	- spartanshields 3.1.1
	- spartanweaponry 3.1.3
	- supplementaries 1.20-2.8.17
		\-- mixinsquared 0.1.1
	- t_and_t 0.0NONE
	- tacz 1.0.2
	- terrablender 3.0.1.7
	- tfmg 0.9.1c-1.20.1
	- valhelsia_core 1.1.2
	- valhelsia_structures 1.20.1-1.1.2
	- vinery 1.4.28
	- warriorsofpastepoch 1.0.0
	- waterframes 2.1.3
	- watermedia 2.0.70
	- yungsapi 1.20-Forge-4.0.5
	- yungsbridges 1.20-Forge-4.0.3
```
But I don't see the Sinytra Connector or any of the other requisite mods to run MCDX on Forge. If this is a case where the requisite mods are missing. This can also be the case where the mod are simply missing from the server but are present on you client. If that is the case, here is a list of the mods that you need to make sure that it will work. Make sure that these mods are on the clients and the server:

## MCDX on Forge
### When using MCDX on Forge, it is important to make sure that you have the following mods:
So, anything marked with a 🟢 is required. Anything marked with a 🟡 is optional

### CurseForge
🟢 Sinytra Connector: 
[https://www.curseforge.com/minecraft/mc-mods/sinytra-connector/](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector/)
🟢 Connector Extras: 
[https://www.curseforge.com/minecraft/mc-mods/connector-extras/](https://www.curseforge.com/minecraft/mc-mods/connector-extras/)
🟢 Forgified Fabric API (in place of the Fabric API): 
[https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api/](https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api/)
🟢 Cloth Config API (Forge or Fabric Version): 
[https://www.curseforge.com/minecraft/mc-mods/cloth-config/](https://www.curseforge.com/minecraft/mc-mods/cloth-config/)
🟡 Clumps (Fabric Version), if you're using Clumps: 
[https://www.curseforge.com/minecraft/mc-mods/clumps/](https://www.curseforge.com/minecraft/mc-mods/clumps/)

### Modrinth
🟢 Sinytra Connector: 
[https://modrinth.com/mod/connector](https://modrinth.com/mod/connector)
🟢 Connector Extras: 
[https://modrinth.com/mod/connector-extras](https://modrinth.com/mod/connector-extras)
🟢 Forgified Fabric API (in place of the Fabric API): 
[https://modrinth.com/mod/forgified-fabric-api](https://modrinth.com/mod/forgified-fabric-api)
🟢 Cloth Config API (Forge or Fabric Version): 
[https://modrinth.com/mod/cloth-config](https://modrinth.com/mod/cloth-config)
🟡 Clumps (Fabric Version), if you're using Clumps: 
[https://modrinth.com/mod/clumps](https://modrinth.com/mod/clumps)

If you need help with anything else, don't hesitate to ask!

**Comment by chronosacaria** [comment]
Due to lack of response, this issue shall be presumed resolved and closed.
