### ISSUE TITLE
Backslot Compat Issue

### ISSUE THREAD

**Issue by Cluelesshobo** [chronosacaria/MCDungeonsWeapons#3]
When MCD weapons are holstered using [BackSlot](https://www.curseforge.com/minecraft/mc-mods/backslot) the weapons appear massive on the character and off-center. Other modded tools and weapons do not have this issue.

**Comment by chronosacaria** [comment]
Oh dear, you're not kidding! I'm looking into this. I wonder what information it is looking for that makes them look so big? I think I know why some of them of off centre, though, so I can fix that pretty easily.

**Comment by chronosacaria** [comment]
I've reached out to Globox_Z and we're working on getting this solved

**Comment by chronosacaria** [comment]
Globox_Z and I were able to resolve all of the render issues! :D
