### ISSUE TITLE
Feature Request: Add weapons to certain tags for better compatability with mods.

### ISSUE THREAD

**Issue by Siuolthepic** [chronosacaria/MCDungeonsWeapons#30]
What I am proposing:
Im am proposing that weapons be added to tags (such as fabric:swords for swords.). so that way mods such as Tiered would be able to find these weapons as valid. Most likely there would have to be custom tags for the unique MCDungeonsWeapons.

How its currently done:
Currently, due to lack of tags, mods such as tiered or other mods that use the tags to find certain items are unable to add their modifications to MCDungeonsWeapons. Which may confuse users who use both mods at once.

Alternatives:
A possible addon datapack for this mod which accomplishes the tag addition

**Comment by BrekiTomasson** [comment]
Any progress on this? It feels like something that should be fairly quick work; all you need to do is add the appropriate files under `resources/fabric/tags/items` and populate them with your items.

**Comment by chronosacaria** [comment]
I have not had a chance as I have been wanting to make some changes to some of the weapons, dealing with health issues, and need to learn how tags work. This is something that is on my agenda to do though. If you can point me to an example, that would be incredibly helpful as I haven't got the first idea of how to do this aspect of what you're describing

**Comment by Siuolthepic** [comment]
Sorry for the late reply, but a good example of what Im talking about is in my Kyanite mod. https://github.com/Siuolthepic/Kyanite/tree/main/src/main/resources/data/fabric/tags/items 
That link should contain tags for each tool and armor type. If you want to see how they would be used on the recieving end, I recommend checking Tiered as it uses these tags for their modifiers.

**Comment by chronosacaria** [comment]
Thank you, so much, for pointing me to an example. And no worries about the late reply. I've been so busy with life stuff I'd not have been able to actually do anything with it anyway. I'll take a look at this and see if I can get this implemented. Thanks, again! :)

**Comment by Siuolthepic** [comment]
I wish you luck, if you need help at all, feel free to DM me on discord at | "Siuol" Appeared#5729 |
