### ISSUE TITLE
[Bug Report]: Crash on startup with Clumps

### ISSUE THREAD

**Issue by LenKagamine** [chronosacaria/MCDungeonsWeapons#300]
### Describe the bug; What happened?

When launching the game with MC Dungeons suite of mods and dependencies along with the Clumps mod, the game crashes.

### Expected Behavior

The game should load and open.

### Mod Version

9.0.4

### Minecraft Launcher

CurseForge

### Operating System

Windows

### Modpack

Custom

### Additional context

Crash Report: https://pastebin.com/DyAT8PmA

latest.log: https://pastebin.com/GvYKkbsV

**Comment by chronosacaria** [comment]
@LenKagamine This only happens if you use the Forge version of Clumps. The mod page for all of MCDX say, very clearly, to use the **Fabric** version of Clumps. This is working as intended. Swap to the Fabric version of Clumps and your issue with be resolved
