### ISSUE TITLE
[Bug Report]: My game crashed due to the sinytra connector

### ISSUE THREAD

**Issue by NeoStarWonV** [chronosacaria/MCDungeonsWeapons#302]
### Describe the bug; What happened?

When I start up my game it crashed

### Expected Behavior

no

### Mod Version

1.20.1

### Minecraft Launcher

Other

### Operating System

Windows

### Modpack

no

### Additional context

[crash-2024-09-29_13.08.57-client.txt](https://github.com/user-attachments/files/17177691/crash-2024-09-29_13.08.57-client.txt)

**Comment by chronosacaria** [comment]
@NeoStarWonV Do you have all of the necessary mods as stated in the FAQ of our mod page? Please do not immediately respond that you do without checking. Apart from configurations that include Valkyrian Skies, we have not found a mod configuration that MCDX do not work with when set up correctly

**Comment by NeoStarWonV** [comment]
I installed all the required mod except for optional mod

**Comment by NeoStarWonV** [comment]
mcda causes crash alike

**Comment by NeoStarWonV** [comment]
wait,I installed clumps,is that casues this everything?

**Comment by NeoStarWonV** [comment]
yes,issue has been completed

**Comment by MiniRaptor** [comment]
> wait,I installed clumps,is that casues this everything?

Same thing, after installing clumps server started to crash on launch.

Here log if someone needs it

[latest.log](https://github.com/user-attachments/files/17746233/latest.log)

**Comment by chronosacaria** [comment]
@MiniRaptor Make sure you're using the Fabric version of Clumps, not the Forge version
