### ISSUE TITLE
[Bug Report]: don't know where to reach out, but logs getting spammed by bee stuff...

### ISSUE THREAD

**Issue by gabepikamole** [chronosacaria/MCDungeonsWeapons#303]
### Describe the bug; What happened?

something with this mod has my logs spammed with something regarding bees. it's been showing up a lot for no reason, and while this crash report (https://mclo.gs/KfAXNAd) isn't due to an issue with this mod, you can see i really get spammed by this mod and the armor version of it too! maybe incompatibility? maybe my modpack is just screwed up? no idea.

### Expected Behavior

i don't know. maybe not getting spammed?

### Mod Version

1.20.1

### Minecraft Launcher

Other

### Operating System

Windows

### Modpack

my own

### Additional context

i'm just curious as to why i'm getting spammed with it, whether it represents a bug or not and so on. again, the crash is not related to the mod, and it seems to work just fine as is, it just crashed randomly although the pack is fully playable. i believe it has to do with the java version i'm using, which is not realted to this mod at all. ty in advance!

**Comment by chronosacaria** [comment]
@gabepikamole So, this is an issue with how Forge sees our BeeEntity. It won't cause any issues and it should be gone once we finish the 1.21.x release; but I totally understand how it can be extremely annoying. But, you've done nothing wrong and there's nothing wrong with your pack. It is just Forge being derpy

**Comment by gabepikamole** [comment]
tgank you for the reply! i was a bit worried since my pack seems to be filled with stuff that shouldn't be there, but i can at least stop worrying about that one :p
