### ISSUE TITLE
[Bug Report]: Ranged Weapon API makes ranged mcdw weapons useless

### ISSUE THREAD

**Issue by SimplyChloe** [chronosacaria/MCDungeonsWeapons#305]
### Describe the bug; What happened?

As mentioned in my previous issue report, I created a separate instance to test loot and weapons from the MCDW mod, I noticed that NOT having the Ranged Weapon API mod installed (which is marked as an optional dependency) allowed for the bows to shoot normally, however, installing the Ranged Weapon API completely destroys how the bows work and even forces all bows "charge" to deal their max damage even if their "drawspeed" is high . For example, the shortbow's animation is much faster than the regular bow, allowing it to shoot faster and deal its max damage, installing Ranged Weapon API not only forces the bow to charge completely even while its animation is already completed, but it also reduces its damage down to 2 and range to almost none.
Video without the Ranged Weapon API mod:
https://github.com/user-attachments/assets/06fc9aae-e068-428d-84a0-4fd3176f6dd7

Video WITH the Ranged Weapon API mod:

https://github.com/user-attachments/assets/83daace1-fde4-47ac-ad28-d2a1a1479fd2

### Expected Behavior

Weapon should behave the same as without the mod while displaying proper values.

### Mod Version

9.0.4

### Minecraft Launcher

Other

### Operating System

Windows

### Additional context

Using Fabric 0.16.7 and Modrinth

**Comment by chronosacaria** [comment]
@JustRyan362 If you install Ranged Weapon API after the fact, you need to delete your configs and let them regenerate. That will fix the issue.

**Comment by SimplyChloe** [comment]
I did delete the configs and ranged weapons still don't work properly, bows still need to fully "charge" even when their animation is done and damage is lower than what mentions.
I can verify that files were created again because the config files display 0 damage for ranged weapons when the api mod is not installed, but after deleting them, installing the api mod, all ranged weapons get a damage number, however, the issue with the animation and range still prevails.

**Comment by SimplyChloe** [comment]
Finally understood it. Sorry for submitting this issue, I've come to the realization that SHORTbows are for indeed short ranges and meant to be shot quickly rather than holding them. Sorry for the inconvenience and thanks for your help.
