### ISSUE TITLE
Prospector enchantment is overpowered

### ISSUE THREAD

**Issue by Fourmisain** [chronosacaria/MCDungeonsWeapons#33]
The Prospector enchantment adds a chance for Emerald drops from any hostile mob.
Each level increases the chance by 25%, up to 75%, and it drops `level` Emeralds.
Note that this means that Prospector III is _9 times_ as effective as Prospector I!

Prospector III drops on average 2.25 Emeralds per mob, which is by far too much.
For example, doing a raid in hard mode can spawn up to 83 mobs, which would make for 186 Emeralds or just shy of 3 stacks(!) on top of what they already drop - and there are much easier and faster ways to kill lots of mobs.

In the modpack I'm currently playing, I had to disable Prospector because I was gaining literally thousands of Emeralds which I would then all throw away because keeping them was basically cheating.
I feel even Prospector I (with 0.25 Emeralds per kill) would have been too much.

I have a few ideas how this enchantment could be balanced a little better.

First of all: The enchantment level shouldn't both linearly increase the drop chance **and** the drop amount, but only one of them so the emerald count doesn't quadratically increase with the enchantment level.

### Idea 1 (Just a nerf)

Each Prospector level could give a 5% chance for 1 Emerald, which would make for 0.15 Emeralds per kill on level III.

A hard mode raid would then "only" give 12 Emeralds.
**But**, since you are always slaying mobs in this game, this still adds up to a lot - an infinite amount - over time.

### Idea 2 (Looting for Illagers?)

In Minecraft Dungeons, the enchantment description says

> increases the chance to get emeralds upon defeating an enemy

When I first saw this enchantment in MCDW, I thought it would only increase the drop chance of mobs which already drop Emeralds, so Looting for Illagers basically - which I thought was a little pointless.

But maybe this is how it should work?

Because then you're not gaining an infinite amount of emeralds (just by playing the game normally), but you have to do hard work (raids) to get them and the drop amount could be higher than the previous suggestion (though still not 3 stacks high).

### Idea 2.1

Instead of Emeralds dropping from Illagers directly, maybe, just maybe, finishing a raid could reward you with a bunch of Emeralds?

### Idea 3 (A little more fun)

This may be something for 1.17, I think it would be fun if instead of occasionally finding an emerald, you could find a sack (aka a Bundle) of emeralds and maybe some gold?
To balance this, the drop chance would need to be much lower and to be sure the player doesn't miss it, it could play a coin clinking sound effect.

(I feel like this will be done in other mods, a lot of them. If not, then I'm doing it.)

---

I don't really like idea 2 myself, because it *kinda is* pointless to have a second Looting and ideas 2.1 and 3 may stray too far from Dungeons.

I feel like no matter what is done to Prospector, I'll probably keep it disabled because it is kinda like having an automatic Emerald farm.

**Comment by chronosacaria** [comment]
Oh wow, I didn't realise that it was that overpowered. I hadn't considered the fact that emeralds already drop from things. I have some fun ideas for 1.17, but I agree that it should be nerfed, for now, if nothing else. Thanks for doing all of that testing and for such a detailed issue report (as usual :)). I'll be looking into this today. Thanks, again!
