### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by boblet101o** [chronosacaria/MCDungeonsWeapons#34]
I am having trouble using the staff of terror how to I use the explosions and is there a way to see a list of all the enchantments and what they do? Thanks

**Comment by chronosacaria** [comment]
There is actually a discord for help which would be easier for you (probably) than using GitHub Issues. The Explosions have a chance to trigger. There is a wiki, it is in the same place you looked for the Issues tab and it is simply called "Wiki". If you'd like to check out the discord, you can find it here: [https://discord.gg/fjJ26wTbS3](https://discord.gg/fjJ26wTbS3)
