### ISSUE TITLE
Feature Request: Disable MC Dungeons Weapons from spawning in Treasure Loot Tables via Config

### ISSUE THREAD

**Issue by jbjornberg** [chronosacaria/MCDungeonsWeapons#35]
Hello, I was hoping you could add a feature (hopefully to Story Mode & Armor as well) to prevent these from spawning in any kind of loot table- so I can make them 100% only attainable from Quests. It'd be a big help, thanks!

**Comment by chronosacaria** [comment]
I like this idea. I'll need to learn how to do it, but I cannot imagine that it would be too hard. Are you making a modpack and if so, are you using KubeJS? If you are, it may be easier to accomplish what you are looking to do using that

**Comment by jbjornberg** [comment]
I am using KubeJS actually! Unfortunately, the Fabric version (maybe the Forge version as well, but I'm not sure..) doesn't have compatibility quite yet with modifying dungeon/chest loot tables. That's the second place I went after checking the config files here haha.

Not sure how the logic works, or if you're allowed to look at code from other mods in the first place haha- but I'm pretty sure EverlastingAbilities had a config that could disable it's totems from spawning in dungeon chests.

**Comment by chronosacaria** [comment]
Oh okay. I'll have to take a look at that. Thanks for the potential direction :)

**Comment by chronosacaria** [comment]
I forgot to ask, but did you mean you'd like to see everything (not just weapons and armours) not be in loot tables? So, for example, the bee can drop a stinger. Ulster you like to see a config option to control that as well?

**Comment by jbjornberg** [comment]
Sorry for the late response, that would be interesting to control as well- but I'm mainly just looking to make the weapons and armors unattainable. I would actually probably still like the items to drop in my personal case, as I might make some of them required for a step in a quest or something along those lines.

I think having control over that would be cool too though!

**Comment by chronosacaria** [comment]
Implemented
