### ISSUE TITLE
shockwave encahntment on whirlwind causes players to not drop loot on death

### ISSUE THREAD

**Issue by JSJBDEV** [chronosacaria/MCDungeonsWeapons#36]
using whirlwind around a friend on a server, the friend died of the explosion and it didnt report it in chat, it also didnt spawn a VanillaDeathChest - I have a feeling its the weapons problem but I an open an issue on vanilladeathchest if you think otherwise

**Comment by chronosacaria** [comment]
Honestly sounds like it could be their issue. It might be that VDC doesn't expect deaths from explosions? Not sure, but I'll look into it 🙂
