### ISSUE TITLE
Negative Proc based enchants effecting other players even with PVP turned off.  v3.0.5

### ISSUE THREAD

**Issue by RhinoInquiring** [chronosacaria/MCDungeonsWeapons#37]
Noticed that Echo, Chains, and other similar enchants still effect other players when PVP is turned off. I have murdered my friends multiple times without even noticing it. Hella funny but still not the greatest. 

To reproduce pick any of the following enchants and have a player stand within the affect range.
Chains
Echo
Ricochet
Shockwave
Swirling

**Comment by chronosacaria** [comment]
When PvP is turned off, there is a setting in the enchants_config that needs to be set to "true" called "aoe_dont_affect_players". This should prevent the issue you're experiencing. I'll leave the issue open for a few days in case, for some reason, you find that it doesn't work.
