### ISSUE TITLE
Echo Enchant affecting Boats/Minecarts/Armor Stands and other Nonliving Entities

### ISSUE THREAD

**Issue by A1Enigma** [chronosacaria/MCDungeonsWeapons#39]
Either when targeting a boat/minecart/nonliving entity or a living entity nearby, harming either one will affect the other. For example, if I kill a cow near a boat, the boat will be broken. Same goes for the other way around, if I destroy a boat and there is a cow nearby, the cow will take damage.

**Comment by chronosacaria** [comment]
Reopened out of caution

**Comment by chronosacaria** [comment]
Fixed with latest version. Forgot to close
