### ISSUE TITLE
Royal Shield is Undefeatable

### ISSUE THREAD

**Issue by A1Enigma** [chronosacaria/MCDungeonsWeapons#40]
The Royal Shield is meant to be a cosmetically better looking shield than the vanilla Minecraft shield and nothing more, however that is not the case. The Royal Shield cannot be disabled by an axe nor anything else that would normally disable it, meaning you can hold up the shield until the durability runs out.

**Comment by chronosacaria** [comment]
This should be resolved in the latest update
