### ISSUE TITLE
Prospector 3 not working on Zombified Piglins

### ISSUE THREAD

**Issue by WolfGangPako** [chronosacaria/MCDungeonsWeapons#47]
I am playing the Vault Hunters Mod pack, dungeons enchantments is part of it.

I have prospector 3 on a diamond sword and I am not getting any emeralds from killing zombified piglins?

It works on endermen, so it is working, just not on zombified piglins?

**Comment by chronosacaria** [comment]
Sorry this took so long for me to respond; I just tested this and I was able to get an emerald to drop from a zombified piglin. I think that the issue you may be running into is that there are several other things that can be dropped from them so they are taking precedence over the emerald drop. If you have done any more testing or are still experiencing this issue, please let me know. Also, if you are playing with any other mods, there could be a conflict; so if you could share your mod list, that would be great 🙂

**Comment by chronosacaria** [comment]
@WolfGangPako, I just realised that this is not in reference to my mod. You are looking for Dungeons Gear which can be found here: https://github.com/Thelnfamous1/Dungeons-Gear/issues
