### ISSUE TITLE
Enigma resonator causing crash with MobZ mobs

### ISSUE THREAD

**Issue by Karrtoffelbaer** [chronosacaria/MCDungeonsWeapons#49]
With Enigma resonator 3 and over around 118 levels of xp on a sword with damage above 11 (vanilla limit on swords I think from tewsting), hitting a mob from the MobZ mod causes the game to crash

**Comment by chronosacaria** [comment]
Could you share the crash report, please?

**Comment by Karrtoffelbaer** [comment]
[crash-2021-06-13_20.18.34-client.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/6644424/crash-2021-06-13_20.18.34-client.txt)

**Comment by chronosacaria** [comment]
This is a problem with XHP, it looks like. You may want to reach out to the author of that mod

**Comment by Karrtoffelbaer** [comment]
Very well thanks a lot :)
