### ISSUE TITLE
crash on startup 1.17

### ISSUE THREAD

**Issue by TheNimbleNinja** [chronosacaria/MCDungeonsWeapons#50]
https://gist.github.com/TheNimbleNinja/b2b0df86e54c5c7ca1634bfc4aa4da6a

**Comment by chronosacaria** [comment]
Could you also post the crash log, please?

**Comment by TheNimbleNinja** [comment]
for some reason its not crashing now i dont know why it crashed in the first place might of been a mod i had and removed causing it
