### ISSUE TITLE
Melee Attacks Ricochet

### ISSUE THREAD

**Issue by ShyCatsu** [chronosacaria/MCDungeonsWeapons#51]
I made a world and modpack with ONLY MCDW to test this, and for some reason, every single time I melee an enemy with my fists, an arrow shoots out of them, as if they were hit by something with ricochet. 

This is my one of my favourite mods, and this is kind of an embarrassing error.

https://user-images.githubusercontent.com/85979537/122157724-f808a400-ce30-11eb-839a-495a48138bd5.mp4
![Capture](https://user-images.githubusercontent.com/85979537/122157762-08208380-ce31-11eb-9186-4c04f201cb91.PNG)

**Comment by ShyCatsu** [comment]
Disabling ricochet in the config does solve the issue, but this is something that should be investigated, if it is going to default to enabled. Thank you.

**Comment by chronosacaria** [comment]
This is fixed in the 1.17 release. Once I fix my 1.16 dev environment, I'll be able to fix this for 1.16. If I cannot fix my dev environment this issue will go unresolved for 1.16

**Comment by ShyCatsu** [comment]
All right, thank you!

**Comment by chronosacaria** [comment]
I am unable to fix my 1.16.5 dev environment, so this issue will go unresolved in 1.16.5. This issue is resolved in 1.17 so this issue will be closed.
