### ISSUE TITLE
keeps crashing 

### ISSUE THREAD

**Issue by erebus227** [chronosacaria/MCDungeonsWeapons#56]
every time i try to load up fabric it says "The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mcdw'!
Exit Code: -1" please help

**Comment by chronosacaria** [comment]
I need the crashlog if I am going to be able to help you

**Comment by chronosacaria** [comment]
As a crashlog as not been provided, I am closing this issue
