### ISSUE TITLE
charge cant be put on anything

### ISSUE THREAD

**Issue by WyLL-Code** [chronosacaria/MCDungeonsWeapons#58]
The charge enchantment cant be put on anything. why.

Modlist:
Mob Origins (by UltrusBot)
Cloth Config API (Fabric) (by shedaniel)
Pehkui (by Virtuoel)
Architectury API (Fabric) (by shedaniel)
AppleSkin (by squeek502)
Bits And Chisels (by cool_mineman)
MC Dungeons Weapons (by chronos_sacaria)
MC Dungeons Armors (by chronos_sacaria)
Fabric API (by modmuss50)
No Enchant Cap (by AmyMialee)
Tax Free Levels (by Fourmisain)
Origins: Classes (by Apace100)
Roughly Enough Items Fabric (REI) (by shedaniel)
Extra Origins (by MoriyaShiine)
Clumps (by Jaredlll08)
Giselbaer's Durability Viewer (by Giselbaer)
Xaero's Minimap (by xaero96)
ToroHealth Damage Indicators (by ToroCraft)
AdventureZ (by Globox_Z)
Genesis - An Origins Addon (by PhantomereLive)
Origins (by Apace100)

**Comment by chronosacaria** [comment]
Have you tried putting it on a bow? It is made for bows and when I checked it worked with them
