### ISSUE TITLE
my friend keeps getting this report when she tries to join our server, please help

### ISSUE THREAD

**Issue by StarAxeMaster** [chronosacaria/MCDungeonsWeapons#59]
Registry remapping failed: Recieved ID map for
minecraft:sound_event contains IDs unknown to the receiver!
- mcdw:echo_sound

I realize that this was already and issue and was closed due to no one responding but if you could help that would be very much appreciated.

**Comment by chronosacaria** [comment]
Sorry for the delay in my response. I was taking a break due to some health issues. 

Which version of MCDW are they using and which version is on the server?

**Comment by chronosacaria** [comment]
This issue will be closed due to lack of response
