### ISSUE TITLE
Bows, Crossbows dont work

### ISSUE THREAD

**Issue by ThebigTijn** [chronosacaria/MCDungeonsWeapons#61]
https://cdn.discordapp.com/attachments/778582541547601931/892463087100264518/mcdw_bug.mp4 just this

**Comment by chronosacaria** [comment]
Whilst I appreciate the video, this is less helpful than it may seem at first. I need to know a number of things:
1. Do you have other mods installed?
2. Are you using a modpack? If so, what is it?
3. What version of MCDW are you using?
4. What version of Minecraft are you using?

Let's start there :)

**Comment by ThebigTijn** [comment]
> Whilst I appreciate the video, this is less helpful than it may seem at first. I need to know a number of things:
> 
> 1. Do you have other mods installed?
> 2. Are you using a modpack? If so, what is it?
> 3. What version of MCDW are you using?
> 4. What version of Minecraft are you using?
> 
> Let's start there :)

Yeah so, the mods I used are in the video. I am on 1.17.1, I am not using a modpack, and it’s the latest on curseforge.

**Comment by chronosacaria** [comment]
Is that all of them? There are no other libraries that don't show up in Mod Menu? I just want to make sure that something isn't missing here. 

I'm thinking that it might be Not Enough Animations causing the issue, but I'll do some testing tomorrow. The issue doesn't exist with just MCDW. 

In the future, though, when providing bug reports, please consider adding a list of the mods. I am partially blind and I cannot read the mods in the video easily

**Comment by Kluzzio** [comment]
List of the mods present in the video:
Apoli
BackSlot
BCLib
BetterEnd
Better Nether
BetterF3 (Client)
Calio
Charmonium (Client)
Dehydration
Enchant Giver
EnvironmentZ
Falling Leaves (Client)
FirstpersonModel (Client)
Improved Stations
MC Dungeons Armors
MC Dungeons Artifacts
MC Dungeons Weapons
Mod Menu (Client)
NotEnoughAnimations (Client)
OptiFabric (Client)
Origins
Origins: Classes
Presence Footsteps (Client)
Puddles
Simple Rpc
YUNG's API
YUNG's Better Strongholds

**Comment by chronosacaria** [comment]
As this is likely an issue with the model mod and the bows and crossbows work with the base mod, this issue shall be closed.
