### ISSUE TITLE
How can I install it ?

### ISSUE THREAD

**Issue by raphdcst** [chronosacaria/MCDungeonsWeapons#62]
I install the three mods of MC dungeons, with Trinkets. But its not work... 
I've a low-end pc but with other mods, its work perfectly, so I think I don't install correctly the mods.

Can anyone help me ?? Thanks <3

(PS : I'm french, so my english isn't perfect I know)

**Comment by chronosacaria** [comment]
Pourriez-vous poster votre crashlog, s'il vous plaît? Ça m'aiderait à diagnostiquer le problème

**Comment by raphdcst** [comment]
Yes, of course. 
[crash-2021-10-13_18.53.44-client.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/7340064/crash-2021-10-13_18.53.44-client.txt)

**Comment by chronosacaria** [comment]
@raphougrr ah, I see the problem. You need to install this mod: [https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/3413206]() and that should solve your issue 🙂

**Comment by chronosacaria** [comment]
As the correction has been issued, this issue shall be closed
