### ISSUE TITLE
Crashing on Initializing game

### ISSUE THREAD

**Issue by Dark-Matter-X** [chronosacaria/MCDungeonsWeapons#63]
[crash-2021-10-17_13.15.32-client.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/7358716/crash-2021-10-17_13.15.32-client.txt)

Game cannot launch due to this error:
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mcdw'!

**Comment by chronosacaria** [comment]
Hi @Dark-Matter-X! It looks like there is a conflict with Limitless. Could you try removing it and seeing if the issue still happens?

**Comment by Dark-Matter-X** [comment]
Thanks! Game is working again.

**Comment by chronosacaria** [comment]
No problem! I'm glad it was an easy fix 🙂
