### ISSUE TITLE
Crashing with LevelZ

### ISSUE THREAD

**Issue by SHXRKIEgg** [chronosacaria/MCDungeonsWeapons#69]
Crash with LevelZ mod I believe, one of my players reported it

[Crash](https://github.com/chronosacaria/MCDungeonsWeapons/files/7746839/crash-2021-12-18_17.51.36-client.2.txt)

**Comment by chronosacaria** [comment]
Hey @SharkieTV! This may need to be fixed on Globox's side. The Glaive is a SwordItem in MCDW's code and it looks like LevelZ is trying to cast it into a MiningToolItem for some reason. Looking at their code, it looks like they are using the tags to assign types of weapons, but the glaives are noted in the swords.json file, so I am even more confused by this. It might be worth reaching out to Globox too if you've not already; but I'll keep looking into this on my end

**Comment by Kiryonn** [comment]
yes i confirm it's levelZ incompatibility. somewhat.
[crash-2021-12-24_01.46.59-client.txt](https://github.com/chronosacaria/MCDungeonsWeapons/files/7771973/crash-2021-12-24_01.46.59-client.txt)

i believe it comes from the strength needed for weapons to be used. might be wrong tho. i'll send an issue to GloboxZ on that one and let you tuned.

**Comment by Globox1997** [comment]
LevelZ uses the fabric tags to determine the item damage.
The crash should only happen with items not included in those tags.
@Kiryonn or @SharkieTV , which exact item cause this crash?

**Comment by chronosacaria** [comment]
Ah, maybe I missed some items in the tags files? I'll check that now

**Comment by chronosacaria** [comment]
I had missed some weapons in the tag files, but it would appear that none of them were Glaives or Hammers like in the crash reports 🤔

**Comment by Globox1997** [comment]
Waiting for those guys to test it :) @chronosacaria do you have a updated version with the missing ones?

**Comment by chronosacaria** [comment]
@Globox1997 I will have an updated version to work with on the first of the year. I have been pretty sick (I got COVID...), but I can also do some testing on my end with LevelZ

**Comment by chronosacaria** [comment]
Didn't mean to close it...Just meant to reference it

**Comment by Nanichan20** [comment]
> @Globox1997 I will have an updated version to work with on the first of the year. I have been pretty sick (I got COVID...), but I can also do some testing on my end with LevelZ

Hope you get better soon dude. saw the reply on curseforge but hasn't been active on it much

**Comment by Globox1997** [comment]
A nice dude suggested a solution on my end, so I will also have a fix for that :)
 @chronosacaria  don't have fear and we both know our god is greater than any sickness, I pray for you brother :)

**Comment by chronosacaria** [comment]
@Globox1997 Amen to that! Thank you so much for your prayers. It means a lot

**Comment by Kluzzio** [comment]
Fixed by Globox : https://github.com/Globox1997/LevelZ/commit/83b1519559f02606466b850ab62b9bb0e2283aac
