### ISSUE TITLE
Reduce Cackling Broom Drop rate

### ISSUE THREAD

**Issue by itsdinkd** [chronosacaria/MCDungeonsWeapons#70]
1.18.1 Fabric

The drop rate for this guy is waaaay too high... please reduce.

**Comment by Kluzzio** [comment]
Received 4 brooms from a single witch so looting is not working properly as well

**Comment by chronosacaria** [comment]
Yeah, I thought I was making it low but clearly I screwed that one up lol :P I'll fix it in the refactor
