### ISSUE TITLE
Ambush does not work properly

### ISSUE THREAD

**Issue by WyLL-Code** [chronosacaria/MCDungeonsWeapons#73]
If ambush does x6 damage when crouching and invisible, it should be able to one shot a piglin brute, however when the weapon is enchanted with sharpness V and Ambush 3, it takes 3 hits with a diamond sword and 2 hits with a Mechanized sawblade

**Comment by Kluzzio** [comment]
Ambush is 1.45x damage at Ambush 3. It is not 6x damage. The damage calculation is also done with attackDamage which is the base damage of the weapon which does not factor in sharpness. The amount that is being done will be modified in the refactor to include the damage done by sharpness. This will result in a slight buff. Around 1.35 extra damage dealt when paired with sharpness V. Certainly nothing to the magnitude of 6x though. This was a confusion by the mod author between void strike and ambush, apologies.
