### ISSUE TITLE
Incompatible with Backslot

### ISSUE THREAD

**Issue by Lordbaane** [chronosacaria/MCDungeonsWeapons#74]
https://bytebin.lucko.me/NCvASg5Bpw
Version 4.0 causes a crash when opening inventory.

**Comment by chronosacaria** [comment]
Yep, I've already reached out to Globox about it. Hopefully we can get this resolved quickly :)

**Comment by chronosacaria** [comment]
This should be fixed now: https://github.com/Globox1997/BackSlot/commit/26603ea6a11a357ee9c2e07d06e5621ca1ba65f7
