### ISSUE TITLE
Innate Enchantments ignore compatibility conflicts with other enchantments

### ISSUE THREAD

**Issue by Kluzzio** [chronosacaria/MCDungeonsWeapons#77]
Innate enchantments are ignoring enchantment conflicts

"Moon dager can get enigma resoanator and void strike without activating the op mixture"
 - Xneverfound🎄

**Comment by chronosacaria** [comment]
I cannot reproduce this on the latest version with the latest fixes outside of creative mode and without OP Mixing enabled. As such, I am going to close this issue.
