### ISSUE TITLE
Soul Devourer has no Description

### ISSUE THREAD

**Issue by Miku0Sama** [chronosacaria/MCDungeonsWeapons#78]
The Soul Devourer Enchantment has no description and I can't figure out what it does.

**Comment by Kluzzio** [comment]
You are absolutely correct, apologies! The soul devourer enchantment multiplies experience received. Experience gained from experience orbs is dependent on the total soul devourer level between your mainhand and offhand weapon (offhand only contributes if it has dual wielding).

The description will be added to the next MCDW release and the wiki will be updated soon!
