### ISSUE TITLE
almost, but not quite, entirely sure this is going in the right place... maybe a mixin problem

### ISSUE THREAD

**Issue by superon** [chronosacaria/MCDungeonsWeapons#8]
been getting a lot of crashes today on the server after updating to latest mcdw
looking into it (asking other people as i can't see what's going on with this sort of thing) it was first suggested "You have a mod with a broken mixin"
another person says "Seems to be a mod that changes something with enchantments" because "method_8180 is Enchantment#canAccept".

only mcdw and curses handle enchants afaik and since this is a new crash i've come here first.
https://pastebin.com/XrahbB7u

idk if it's worth mentioning that i'm not using nbtcrafting on the client either though had previously for 2.0.4 on the same server, hopefully not worth mentioning and not worth responding to :)

of course anything i can do my end to help you pls do ask.   it has been suggested that i disable all other mods before sending a crash report by someone else though i hope you can see this would be a huge undertaking on my part, or at least i can't imagine how to do this in a simple way right now.. apologies for the extra waffle

**Comment by chronosacaria** [comment]
I'm not really sure. None of mixins use that method, though. I'm sorry, but, to be sure, you'd have to either remove my mod to see if the issue persists or turn everything else off. 

An easy way to do it is to make an instance (either with Curseforge, MultiMC, etc.) and test with only my mod.

Could you explain what you were doing when it happened? Did you have one of my weapons? Did the item have a curse? Did the item have any of my enchantments? That might help narrow it down.

No need to apologise. You finding bugs, if they are my fault, help me make my mod better. You're being respectful, so there is no reason to apologise. 🙂

**Comment by superon** [comment]
ahhh ok np, i can load up another instance or first try disabling curses, curses being the other mod to handle enchants..
i was doing alsorts, nothing specific... mostly crafting items but also just exploring :/  was really testing for this at the time though so i can direct efforts more towards this issue another time.

i did have a red bow, i forget the name right now but will get back on that.  it was not enchanted with anything.
it will be probably another day before i can put time into checking these things now, i need to set up another server instance as it seems that crashes but the client is fine with whatever is thrown at it.     also i have added a fair amount of mess myself so won't be too surprised if i mashed it too hard somewhere

**Comment by superon** [comment]
red snake

**Comment by chronosacaria** [comment]
lol, no worries. Just let me know if you whatever you find 🙂

**Comment by chronosacaria** [comment]
It is worth noting that no bows should have any innate enchantments

**Comment by superon** [comment]
:) i have removed all of the crafting recipes from mcdw and instead have them attainable as dungeon loot items if that makes a difference

**Comment by superon** [comment]
also just seeing it could actually even be this thing https://www.curseforge.com/minecraft/mc-mods/infinity-water-bucket

**Comment by chronosacaria** [comment]
It very well could be the Infinity Water Bucket after looking at the mixin. Having the Mcdw weapons only attainable via loot should have no impact on anything related to mixin issues, though

**Comment by chronosacaria** [comment]
Changed tag and closed issue as it was determined to have been caused by Infinity Water Bucket and has been resolved according to alkyaly (https://github.com/alkyaly/Infinity-Water-Bucket/issues/2#issuecomment-739852112).
