### ISSUE TITLE
Repairing Weapons

### ISSUE THREAD

**Issue by mropitzky** [chronosacaria/MCDungeonsWeapons#80]
Hello! I noticed today today when i went to repair a weapon, there was no easy way to do so other than making another copy and throwing it into the anvil. The issue with that is that most have bas enchantments on them allready, which jacks the price of repair up astronomically since yoru technically enchanting it. My question is, is there another way to repair these weapons that im just not seeing. thank you!

**Comment by Kluzzio** [comment]
Weapons can be repaired with specific items. You can see these items required for specific weapons in the mcdw_stats_config file under material. If these do not appear for you, you are using an older version. Seeing as how this is not a current issue, I will close this issue.
