### ISSUE TITLE
Fishing Rod Enchantments

### ISSUE THREAD

**Issue by ThinkWithPbody** [chronosacaria/MCDungeonsWeapons#82]
![image](https://user-images.githubusercontent.com/51525460/150054937-8b700001-b117-4622-af90-c2398e6e0aee.png)
Please forgive me for not giving the fullest details. In short, enchantments such as Echo, Soul Siphon, Leeching, Rampaging, Swirling... can be applied to fishing rods when using an enchantment table. This surely can't be the intented behaviour?

**Comment by ThinkWithPbody** [comment]
I just found out that these enchantments can be applied to pickaxe and other tools too when using an enchantment table. From this I can assume it is their expected behaviour, but I still think it would make more sense to have them only applied to weapons and books when enchanting normally through enchantment tables, so you wouldn't have to end up with an Echo 3 Unbreaking 3 pickaxe.

**Comment by Kluzzio** [comment]
Could you say what version you are using? @ThinkWithPbody
If it is indeed the latest, we will look into it soon.

**Comment by ThinkWithPbody** [comment]
I was using the latest version available for 1.18.1 on curseforge, with mcda-1.9.0.jar, mcdar-1.4.3-1.18.jar, and mcdw-4.0.2.jar. I am however using 145 vanilla-style fabric mods in total, mostly being cosmetic with no mods adding or altering the enchantments in any way other than Bow Infinity Fix. I can try to narrow it down if required.
