### ISSUE TITLE
Combat ecnhantemnts are tagged as Tools

### ISSUE THREAD

**Issue by RedWideWeb** [chronosacaria/MCDungeonsWeapons#85]
Since version 4.0.0 Combat enchantments like Void Strike are tagged as Tools.

3.6.0
![изображение](https://user-images.githubusercontent.com/58992150/150686861-38c35875-6ae2-4ae2-9d59-a6ee8318f5f4.png)

4.0.0
![изображение](https://user-images.githubusercontent.com/58992150/150686875-f91bd222-4779-4714-b01c-5151b9e5c9ad.png)

This issue makes enchantment frustrating experience.

**Comment by Kluzzio** [comment]
This is likely the cause for (#82)

**Comment by chronosacaria** [comment]
🤦‍♂️

**Comment by RedWideWeb** [comment]
> 🤦‍♂️

Is this going to take long to fix, @chronosacaria ?

**Comment by chronosacaria** [comment]
No. I'm gonna look at it tomorrow/today after I get some sleep

**Comment by RedWideWeb** [comment]
> No. I'm gonna look at it tomorrow/today after I get some sleep

Great! Thank you!

**Comment by RedWideWeb** [comment]
> This is likely the cause for (#82)

You are absolutely right. It's strange though how come Void Strike can still be applied to Chestplates? Chestplates are Combat. So are the enchantments tagged with Tools and Combat but the game only shows the first one?
