### ISSUE TITLE
ticking entity after having hit it too good

### ISSUE THREAD

**Issue by superon** [chronosacaria/MCDungeonsWeapons#9]
i think :/
mcdw-2.0.5
https://pastebin.com/93kA6ee2
crashes the server and insta crashed again after launching

**Comment by chronosacaria** [comment]
Hi again, superon. You really can't catch a break can you. Yes, this one looks like it is on me. Did the Piglin get a hold of a sword with critical hit on it? It says that the piglin couldn't get cast into the player, and the enchantment is expecting the player to be using it not the piglin. I can work on getting this fixed. I'm going to try to reproduce it so I can see exactly what is going on.

**Comment by chronosacaria** [comment]
I just released something that should fix it. It should be approved by Curseforge soon.

**Comment by superon** [comment]
piglin ay?   i was in the nether but was battling blazes at the time :)   i just assumed it was the player ticking (even though the report didn't say player) because i installed not enough crashes to see and that resulted in exploding me, turning the surrounding area into a firescape that burnt most of my items.   lawks
thanks again, we'll get this good
