### ISSUE TITLE
Royal guard shield cannot be repaired

### ISSUE THREAD

**Issue by AragoonKappa** [chronosacaria/MCDungeonsWeapons#91]
The Royal Guard shield can not be repaired with diamond as it should :

![image](https://user-images.githubusercontent.com/25965310/153494476-bcd96ebd-0f59-4c28-bee0-c8516fe49583.png)

Other shields might be affected, not tested.

MCDW version 4.0.4, Fabric 0.12.12

**Comment by Kluzzio** [comment]
![image](https://user-images.githubusercontent.com/96443090/153513433-9ba50994-5edc-4412-b477-bd35b0dd58d2.png)
Fixed! :)
