### ISSUE TITLE
[Feature Request] Material ID for Datapack with LevelZ mod -> where to find material id in mcdw -> in mcda i found it  

### ISSUE THREAD

**Issue by xR4YM0ND** [chronosacaria/MCDungeonsWeapons#93]
I wanna know where i can find the "material id" for every sword / weapon 

I'm making a datapack for the mod "LevelZ" 

Looks like:
{
    "replace": true,
    "skill": "strength",
    "level": 1,
    "item": "minecraft:sword",
    "material": "?"
}

The question is what i type for "material"

I found something like "SWORD_HEARTSTEALER" but it doenst work.  

Your Armor Mod has some lower case like "souldancer" which works fine with LevelZ but with mcdw i cant figure out which material to use. 

Pls let me know where to find these

**Comment by Kluzzio** [comment]
The repair ingredient (material) is dependent based on what the toolMaterial is. You can find this for every weapon in the McdwNewStatsConfig.java file.
This is the file path.
![image](https://user-images.githubusercontent.com/96443090/154016256-8446efd6-e3e5-4ed8-b082-c96d8b22f6a4.png)

**Comment by Kluzzio** [comment]
Do let me know if that is what you were looking for. If not, some further clarification with what you found on MCDA would be great! Thanks @SpigotDE

**Comment by xR4YM0ND** [comment]
aaaah its bound on wood / iron /diamond and so on.. ok now i understand. 

In MCDA you have extra bindings : 

https://github.com/chronosacaria/MCDungeonsArmors/blob/1.18/src/main/java/chronosacaria/mcda/items/ArmorSets.java

For Example i can add:

{
"replace": true,
"skill": "strength",
"level": 1,
"item": "minecraft:armor",
"material": "archer"
}

With MCDW i have to add for example:

{
"replace": true,
"skill": "strength",
"level": 1,
"item": "minecraft:sword",
"material": "iron"
}

or netherite or so on.. ok

i thought i can give every sword a different class in "level" 

When you quickly watch on LevelZ's wiki -> you can set level limit before i can use the item

https://github.com/Globox1997/LevelZ

I understand what i can add but is there hope that you make it similar as in MCDA?

**Comment by xR4YM0ND** [comment]
If you dont know what i mean we can quickly discord or something else

**Comment by xR4YM0ND** [comment]
SpigotDE#8841

**Comment by Kluzzio** [comment]
Alright, I sent you a friend request on discord so that we can converse what exactly you'd like there.  I was hoping you could explain what you'd like a little more, so I can discuss it with Chronos. My discord is Amphibatron#5091. @SpigotDE

**Comment by Kluzzio** [comment]
Alternatively, you can also join Chronos' discord which you can find the link to on curseforge or the wiki page.

**Comment by Kluzzio** [comment]
![image](https://user-images.githubusercontent.com/96443090/156190902-f2c0fdfc-1a68-4075-b533-d339f0486b1b.png)
From Globox, maker of LevelZ. That feature will be added on their end @SpigotDE

**Comment by Kluzzio** [comment]
I will close this comment when there is confirmation that this works with mcdw. The change will happen on LevelZ's update with their 1.2.0 release

**Comment by xR4YM0ND** [comment]
[Confirmed] works as planned - thx <3
