### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by KingPigStep** [chronosacaria/MCDungeonsWeapons#95]
the custom enchantments in dungeon mcwp are rly good but u can only turn it off permanently or turn them on permanently, personally id like a gamerule that makes its so u can disable normal way to get those enchantments like finding in structures (or only really rare ones) and enchanting, like : /gamerule DoPlayersFingCustomEnchants false/true

you could also make another command that disable custom enchants for some people like /CE disable (player IGN)

**Comment by Kluzzio** [comment]
After some consideration, we have decided that this is not something that we will implement. The reasons for this decision are that the situation in which this would be used are incredibly niche, it is reasonably difficult to implement, and it would bloat the size of MCDW unnecessarily. Considering that the majority of servers make decisions on enchantments at the creation and have no interest in changing this while the server is open, this is just too specific of a scenario. We may however make a gamerule or config in the future that does something to this general effect in a more broad sense, such as controlling whether enchantments are considered to be treasure enchantments or not. Regardless, thank you for your suggestions.
