### ISSUE TITLE
Axolotl issue

### ISSUE THREAD

**Issue by liwiss** [chronosacaria/MCDungeonsWeapons#97]
Every time an axolotl defeats an underwater mob the game crashes. When reloading the world runs perfectly. I don't know if it has to do with some compatibility issues, but i've created an instance of the game only containing this mod and the same thing happens.
Here's the crash report in the moded version.

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 3/2/22, 6:38 PM
Description: Ticking entity

java.lang.ClassCastException: class net.minecraft.class_5762 cannot be cast to class net.minecraft.class_1657 (net.minecraft.class_5762 and net.minecraft.class_1657 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @255b53dc)
	at net.minecraft.class_1309.handler$dhb001$mcdw$onDeath(class_1309.java:21190)
	at net.minecraft.class_1309.method_6078(class_1309.java)
	at net.minecraft.class_1309.method_5643(class_1309.java:1177)
	at net.minecraft.class_5762.method_6121(class_5762.java:383)
	at net.minecraft.class_4816.method_24590(class_4816.java:50)
	at net.minecraft.class_4816.method_18920(class_4816.java:17)
	at net.minecraft.class_4097.method_18922(class_4097.java:49)
	at net.minecraft.class_4095.method_18891(class_4095.java:511)
	at net.minecraft.class_4095.method_19542(class_4095.java:470)
	at net.minecraft.class_5762.method_5958(class_5762.java:356)
	at net.minecraft.class_1308.method_6023(class_1308.java:758)
	at net.minecraft.class_1309.method_6007(class_1309.java:2604)
	at net.minecraft.class_1308.method_6007(class_1308.java:545)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at net.minecraft.class_1429.method_6007(class_1429.java:58)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.minecraft.class_1308.method_5773(class_1308.java:345)
	at net.minecraft.class_3218.redirect$eim000$shouldTickEntity(class_3218.java:9680)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1309.handler$dhb001$mcdw$onDeath(class_1309.java:21190)
	at net.minecraft.class_1309.method_6078(class_1309.java)
	at net.minecraft.class_1309.method_5643(class_1309.java:1177)
	at net.minecraft.class_5762.method_6121(class_5762.java:383)
	at net.minecraft.class_4816.method_24590(class_4816.java:50)
	at net.minecraft.class_4816.method_18920(class_4816.java:17)
	at net.minecraft.class_4097.method_18922(class_4097.java:49)
	at net.minecraft.class_4095.method_18891(class_4095.java:511)
	at net.minecraft.class_4095.method_19542(class_4095.java:470)
	at net.minecraft.class_5762.method_5958(class_5762.java:356)
	at net.minecraft.class_1308.method_6023(class_1308.java:758)
	at net.minecraft.class_1309.method_6007(class_1309.java:2604)
	at net.minecraft.class_1308.method_6007(class_1308.java:545)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at net.minecraft.class_1429.method_6007(class_1429.java:58)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.minecraft.class_1308.method_5773(class_1308.java:345)
	at net.minecraft.class_3218.redirect$eim000$shouldTickEntity(class_3218.java:9680)
	at net.minecraft.class_3218.method_18762(class_3218.java:699)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)

-- Entity being ticked --
Details:
	Entity Type: minecraft:axolotl (net.minecraft.class_5762)
	Entity ID: 302
	Entity Name: Axolotl
	Entity's Exact location: 245.81, 1.24, 77.91
	Entity's Block location: World: (245,1,77), Section: (at 5,1,13 in 15,0,4; chunk contains blocks 240,-64,64 to 255,319,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.14, 0.14, 0.08
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:360)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:328)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['liwiss'/1, l='ServerLevel[Mundo creaciones]', x=249.07, y=0.00, z=76.00]]
	Chunk stats: 3408
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,0,0), Section: (at 0,0,0 in 0,0,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 5949649 game time, 6000 day time
	Level name: Mundo creaciones
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1187491248 bytes (1132 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 4.01
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 980
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x13c0
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5671
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 28384.64
	Virtual memory used (MB): 25744.72
	Swap memory total (MB): 12040.85
	Swap memory used (MB): 2981.84
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
		apoli: Apoli 2.2.2
		apugli: Apugli 1.4.0
		aqupdcaracal: Caracal mob 1.18-1.3.5.1
		architectury: Architectury 3.7.26
		artifality: Artifality 0.5.5
		attributefix: AttributeFix 13.0.5
		automated_crafting: Automated Crafting 1.4.3-a1
		bclib: BCLib 1.3.4
		bendy-lib: Bendy api 2.0.4
		betterazalea: Better Azalea 1.0.1-SNAPSHOT
		betterbeds: Better Beds 1.2.0
		betterenchantmentboosting: Better Enchantment Boosting 1.1.0
		betterend: Better End 1.0.2
		betterimpaling: Better Impaling 2.0.4
		betterspawnercontrol-fabric: Better Spawner Control (Fabric) 1.5
		betterthirdperson: Better Third Person 1.6.0
		biomeinfo: Biome Info 1.18-8
		blue_endless_jankson: jankson 1.2.1
		bookshelf: Bookshelf 12.0.20
		bountiful: Bountiful 2.0.1
		caffeineconfig: CaffeineConfig 1.0.0
		calio: Calio 1.4.2
		capybara: Capybara 1.0.1
		cardinal-components-base: Cardinal Components API (base) 4.1.2
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.1.2
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		carrier: Carrier 1.9.1
		cem: Custom Entity Models 0.7.0
		chipped: Chipped 1.2
		chord: Chord 1.8.0+1.18-fabric
		chunky: Chunky 1.2.164
		citresewn: CITResewn 0.9.1+1.18.1
		cloth-api: Cloth API 3.1.61
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 3.1.61
		cloth-common-events-v1: Cloth Common Events v1 3.1.61
		cloth-config: Cloth Config v6 6.2.57
		cloth-datagen-api-v1: Cloth Datagen v1 3.1.61
		cloth-scissors-api-v1: Cloth Scissors API v1 3.1.61
		cloth-utils-v1: Cloth Utils v1 3.1.61
		clumps: Clumps 8.0.0+5
		collective-fabric: Collective (Fabric) 4.9
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		comforts: Comforts 1.0.2-1.18.1
		config2brigadier: Config to Brigadier 1.0.2
		controlling: Controlling For Fabric 9.0+15
		coolershields: Cooler Shields 2.4.0
		copper_pipe: Simple Copper Pipes r1.8
		cosmetic-armor: Cosmetic Armor 1.2.1
		crowdin-translate: CrowdinTranslate 1.4+1.18
		cse: Craftable Spawn Eggs 1.0.0
		darkpaintings: DarkPaintings 9.0.3
		dual_riders: DualRiders 1.0.5
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		emotecraft: Emotecraft 2.1
		enchant_giver: Enchant Giver 1.1.0
		enchantedbookredesign: Enchanted Book Redesign 1.17.1-2.0
		enchdesc: EnchantmentDescriptions 9.0.11
		expandability: ExpandAbility 5.0.0
		explorerscompass: Explorer's Compass 1.18.1-2.0.2-fabric
		extraalchemy: Extra Alchemy 1.7.0
		extraorigins: Extra Origins 1.18-9
		fabric: Fabric API 0.46.4+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.8+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.6+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.6+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.11+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.4+d7c144a865
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.12+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.14+713c266865
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.8+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.8+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.9+d7c144a865
		fabricloader: Fabric Loader 0.13.1
		fabricshieldlib: Fabric Shield Lib 1.5.0-1.18
		fabrictailor: Fabric Tailor 1.8.0
		fallingleaves: Falling Leaves 1.9.0+1.18.1
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 1.0.1+1.18.1
		fiber: fiber 0.23.0-2
		fixedwaterlogging: Fixed Waterlogging 1.0.2
		flytre_lib: FlytreLib 1.7.1
		forgeconfigapiport: Forge Config API Port 3.1.1
		friendsandfoes: Friends&Foes 1.2.5
		geckolib3: Geckolib 3.0.33
		goldenhoppers: Golden Hoppers 1.2.0
		golemancy: Golemancy 1.2.4
		goosik-config: goosik-config 0.2.0
		hplus: Hopper Plus 3.1.2
		icarus: Icarus 1.9
		iceberg: Iceberg 1.0.38
		identity: Identity 1.16.0-1.18.1
		invisframes: Invisible Frames 2.1.1
		iris: Iris 1.2.0-pre
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		justmobheads-fabric: Just Mob Heads (Fabric) 5.2
		justplayerheads-fabric: Just Player Heads (Fabric) 1.8
		kambrik: Kambrik 3.0.1-1.18
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		legendarytooltips: Legendary Tooltips 1.2.4
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 5.1.0+1.18
		libninepatch: LibNinePatch 1.1.0
		litematica: Litematica 0.10.2
		litematicatool: Litematia Tool 1.3.2
		lithium: Lithium 0.7.8
		llamarama: Llamarama 1.5.3
		lovely_snails: Lovely Snails 1.0.3+1.18
		malilib: MaLiLib 0.11.7
		mcda: MC Dungeons Armors 2.0.3
		mcdar: MC Dungeons Artifacts 1.4.3-1.18
		mcdw: MC Dungeons Weapons 4.2.0
		mcwpaintings: Macaw's Paintings 1.0.2
		medievalorigins: Medieval Origins 1.18.x-3.3.1
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		mob_catcher: Mob Catcher 1.1.24
		moborigins: Mob Origins 1.8.0
		mobscarecrow: Mob Scarecrow 1.2.0
		modid: Creatures Of The Snow 1.0.0
		modmenu: Mod Menu 3.0.1
		morebannerfeatures: More Banner Features 1.1.3
		morediscs: MoreDiscs 1.18.1.2
		morevillagers-fabric: MoreVillagersFabric 3.1.1-SNAPSHOT
		mousetweaks: Mouse Tweaks 2.22
		musica: Musica 1.5.0
		mythic-mounts: Mythic Mounts 1.18-5.0
		nametagtweaks-fabric: Name Tag Tweaks (Fabric) 1.7
		naturescompass: Nature's Compass 1.18.1-2.0.2-fabric
		no_null_processors: No Null Processors - Fabric 2.0.1+1.18.1
		notenoughanimations: NotEnoughAnimations 1.4.0
		npcvariety: NPC Variety 2.2.2
		omega-config: OmegaConfig 1.2.2-1.18.1
		org_anarres_jcpp: jcpp 1.4.14
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		origins: Origins 1.3.1
		owo: oωo 0.5.2+1.18
		paintings: Paintings++ 9.1.0.0
		patchouli: Patchouli 1.18.1-65-FABRIC
		pehkui: Pehkui 3.1.0+1.14.4-1.18.1
		pettable: Pettable 1.2.1
		phosphor: Phosphor 0.8.1
		pisces: Pisces 1.0.0+1.16.4
		playerabilitylib: Pal 1.5.0
		plushies: Plushie Mod 1.1
		polymorph: Polymorph 0.0.19-1.18.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.1.0
		redstonebits: Redstone Bits 1.7.0
		reeses-sodium-options: Reese's Sodium Options 1.4.0
		replaymod: Replay Mod 1.18.1-2.6.3
		repurposed_structures: Repurposed Structures 3.3.12+1.18.1
		roughlyenoughitems: Roughly Enough Items 7.3.435
		seedfix: Seed Fix 1.0.0
		servercore: ServerCore 1.2.8-1.18.1
		setworldspawnpoint-fabric: Set World Spawn Point (Fabric) 1.8
		silkspawners: SilkSpawners 1.1.0
		simple_backpack: SimpleBackpack 1.2.31
		skinnedlanterns: Skinned Lanterns 1.2.0+build.12
		skyvillages: Sky Villages 1.0.1-1.18.1-fabric
		slime_sling: SlimeSling 1.0.0
		slimechunkf3: SlimeChunkF3 1.3
		socketwrench: Socket Wrench 1.3.0+1.18.1
		socketwrenchitem: Socket Wrench Item 1.3.0+1.18.1
		sodium: Sodium 0.4.0-alpha6+build.14
		sodium-extra: Sodium Extra 0.4.0
		spark: spark 1.8.6
		statement: Statement 4.2.1+1.14.4-1.18.1
		statement_vanilla_compatibility: Statement Vanilla Compatibility Module 1.0.1+1.16.5-1.17
		stoneholm: Stoneholm 1.4.2
		team_reborn_energy: Energy 2.2.0
		terralith: Terralith for Fabric 2.0.12
		things: Things 0.2.15+1.18
		tooltipfix: ToolTip Fix 1.0.4-1.18
		toomanyorigins: TooManyOrigins 0.4.1
		tpcrosshair: Third Person Crosshair 1.2.1
		trade_cycling: Trade Cycling 1.18.1-1.0.2
		transferpet: Pet Transfer 0.0.5
		transportables: Transportables 1.1
		trinkets: Trinkets 3.2.0
		tweakeroo: Tweakeroo 0.12.3
		twigs: Twigs 1.1.2
		villager-hats: Villager Hats Mod 1.3.1
		villagernames: Villager Names 3.0.3
		villagers-follow-emeralds: Villagers Follow Emeralds 1.2.0
		visuality: Visuality 0.4.1
		vmp: Very Many Players 0.2.0+beta.3.8
		voicechat: Simple Voice Chat 1.18.1-2.2.24
		waystones: Waystones 2.4.1
		wilderworld: WilderWorld 1.1.1
		worldedit: WorldEdit 7.2.9+e20e013
		xaeroworldmap: Xaero's World Map 1.20.3.1
		xp_storage: XP Storage 1.4.3+1.18
		xp_storage_trinkets: XP Storage - Trinkets 0.1+1.18
		zombiehorsespawn-fabric: Zombie Horse Spawn (Fabric) 3.0
	Server Running: true
	Player Count: 1 / 8; [class_3222['liwiss'/1, l='ServerLevel[Mundo creaciones]', x=249.07, y=0.00, z=76.00]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

**Comment by chronosacaria** [comment]
Thank you, so much! There were some issues that another person was having but we couldn't pin them down. We're looking at this right now

**Comment by chronosacaria** [comment]
Okay! We fixed it. I'll be pushing the update now

**Comment by chronosacaria** [comment]
https://github.com/chronosacaria/MCDungeonsWeapons/commit/e7f6cb59895073e5fd5948b9ebc8b51ef050e985

**Comment by liwiss** [comment]
thanks!
