### ISSUE TITLE
[1.18.1 Crash] crash on launch due to mixin

### ISSUE THREAD

**Issue by itsdinkd** [chronosacaria/MCDungeonsWeapons#98]
**Describe the bug**
Mixin crash when launching game from my modpack, AQM2 with the latest mcdw update

**Please complete the following information:**
 - MCDW v4.2.1

**Additional context**
crash log; https://gist.github.com/itsdinkd/184c7178fe5bc9ebb41257727e9dedeb

**Comment by chronosacaria** [comment]
@itsdinkd Is this the latest version of AQM2 that was released or is this a pre-release?

**Comment by chronosacaria** [comment]
I also need full crash reports so that I can see versions of the mods you are using. Having the stacktrace is useful for determining _what_ is going on, but in a situation like this, where something is conflicting, without knowing what is in there, I can't really do anything about it
